### ISSUE TITLE
Prosis Pro Tab

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#10]
![image](https://cloud.githubusercontent.com/assets/26387044/24017230/287c388c-0a5d-11e7-85d4-f84f65590f24.png)

Where do you mark if they are paying yearly, 6 month or monthly for Prosis?

**Comment by omnitekinc** [comment]
Sagar,
please add payment plan on the top bar. The logic should be:
Annaly: Expire in 12 months
6 months: Expire 6 months
monthly: Expire end of the month
![287c388c-0a5d-11e7-85d4-f84f65590f24](https://cloud.githubusercontent.com/assets/7178461/24053658/faffaade-0af6-11e7-9142-90259d8cbd7e.png)

**Comment by kbt1** [comment]
It should be just like Membership:
Payment Plan 6 Months
Prosis Due $
Amount Accrued $

Payment plans are: Annually, 6 Month, Monthly
