### ISSUE TITLE
Membership Tab - Search box

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#100]
My search box disappeared??? I signed out and logged back in and still gone.

![image](https://cloud.githubusercontent.com/assets/26387044/24976614/c7f8db30-1f8f-11e7-8cc7-3b09c16c0d83.png)

**Comment by kbt1** [comment]
logged out again and it is back. not sure this needs to be looked at.

**Comment by sagarjagdish** [comment]
There is design issue with last update. We resolved this issue and uploaded in stage. Please verify and confirm.

**Comment by kbt1** [comment]
good to go.
