### ISSUE TITLE
Prospect Tab

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#101]
Prosis Demo users dont seem to have a zip code field so if you convert them to a Membership there is no zip code, can you pull the zip code from the demo user list?
![image](https://cloud.githubusercontent.com/assets/26387044/24977790/f1cfa106-1f93-11e7-9524-1718d45e6fe1.png)

my spreadsheets that i get emailed weekly have the zip code field.
[Sign up User List _07-04-2017.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/917767/Sign.up.User.List._07-04-2017.xlsx)

Not sure what the edit button is for, it works on some and does nothing on others
![image](https://cloud.githubusercontent.com/assets/26387044/24977955/8cd625da-1f94-11e7-9042-5d8bd8a58af4.png)

**Comment by sagarjagdish** [comment]
+++++++++++++
Prosis Demo users dont seem to have a zip code field so if you convert them to a Membership there is no zip code, can you pull the zip code from the demo user list?
+++++++++++++
I have added zip code as per requirement and shown zip code inside that textbox if available for prospect or demo users.

+++++++++++++
Not sure what the edit button is for, it works on some and does nothing on others
+++++++++++++
It's for edit demo user and prospect user, there is no edit function for the conference attendee. conference attendee edit function is something different from demo user and prospect and we already provided edit conference attendee function inside conference tab. So if required we can edit conference attendee from that screen. see below image for reference.

Please let me know if any change required in this.

![image](https://cloud.githubusercontent.com/assets/7322922/25044656/67beb11a-2145-11e7-9964-00778dc73abf.png)

**Comment by kbt1** [comment]
works now - understand edit feature.
