### ISSUE TITLE
Print Invoice vs Email Invoice

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#102]
ID#44237
Print Invoice looks like this:
![image](https://cloud.githubusercontent.com/assets/26387044/24978220/7dcf18a2-1f95-11e7-84a7-a1987981e667.png)

Email invoice looks like this:
![image](https://cloud.githubusercontent.com/assets/26387044/24978249/95304eb2-1f95-11e7-8488-25d64b136bb9.png)

Prosis Pro 30 Day trials should not come up on any invoicing unless converted to a single user or multi user.  
The print and email invoice should be the same.

Also, can we have the ability to edit the invoice without changing in membership record. Sometimes i get a wife who isnt at the shop and wants an invoice emailed to home.

**Comment by omnitekinc** [comment]
karen, do you mean the ability to email the invoice to a different email?

**Comment by kbt1** [comment]
yes-

**Comment by kbt1** [comment]
I just noticed the expiration date being pulled into the email invoice is wrong.
![image](https://cloud.githubusercontent.com/assets/26387044/25052521/dc264e10-2117-11e7-8261-51eaef450e31.png)

Also, if we have an additional contact "Billing", email should default to that.

**Comment by sagarjagdish** [comment]
I just noticed the expiration date being pulled into the email invoice is wrong.
=> resolved this issue please verify and confirm.

![image](https://cloud.githubusercontent.com/assets/7322922/25216220/313e9a96-25bf-11e7-9106-f51486bb4278.png)

@kbt1  :
Also, if we have an additional contact "Billing", email should default to that.
=> It means like if any additional contact available with "Accounting" like below then we should display main member email and additional accounting person email both in as default email for invoice email. correct?

![image](https://cloud.githubusercontent.com/assets/7322922/25216389/f940f9bc-25bf-11e7-8a20-1e0fa8c2715f.png)

**Comment by kbt1** [comment]
Email, it should use both default and accounting emails.

I just noticed the expiration date being pulled into the email invoice is wrong.
=> resolved this issue please verify and confirm.  THIS IS GOOD!

**Comment by kbt1** [comment]
I also noticed when i print an invoice, it looks like there is extra space between the company name and address. Can you check this out.
![image](https://cloud.githubusercontent.com/assets/26387044/25235342/75c07f78-25aa-11e7-8268-a16ceef883a1.png)

**Comment by sagarjagdish** [comment]
Also, if we have an additional contact "Billing", email should default to that. Email, it should use both default and accounting emails.
=> done
![image](https://cloud.githubusercontent.com/assets/7322922/25290007/b528edcc-26e9-11e7-9448-9ff1974d8bfb.png)

I also noticed when i print an invoice, it looks like there is extra space between the company name and address. Can you check this out.
=> done
![image](https://cloud.githubusercontent.com/assets/7322922/25290014/bb70f1e8-26e9-11e7-8e30-ba641ffc53ab.png)

**Comment by kbt1** [comment]
both correct.
