### ISSUE TITLE
Tech Calls

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#104]
drop down box labeled "Tech Calls"   - add Prosis Pro and take out Prosis SA to drop down options

![image](https://cloud.githubusercontent.com/assets/26387044/25053293/07e876aa-211c-11e7-8eba-0153286ff868.png)

**Comment by sagarjagdish** [comment]
added Prosis Pro and removed Prosis SA to drop down options

![image](https://cloud.githubusercontent.com/assets/7322922/25181702/fac7a6d6-252f-11e7-9064-7b7076c243c3.png)

**Comment by kbt1** [comment]
correct
