### ISSUE TITLE
Membership - Mail Code Drop Down Box

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#105]
can you add another option to the drop down box:

Non Payment-Monthly

this way i can put that in and  we will know their payment didnt get approved multiple months if they are on the monthly payment plan. Otherwise, i think people will question how someone is on the monthly payment plan with an expired date other then canceling or not renewing.

**Comment by sagarjagdish** [comment]
We have added new source. Pleas let us know if we need to take any other action based on that new source.

![image](https://cloud.githubusercontent.com/assets/7322922/25181908/a94acdaa-2530-11e7-8055-2f66f6837a32.png)

**Comment by kbt1** [comment]
please remove from the Membership Source box and place in **Mail Code box**
membership is suspended if this option is selected. 
![image](https://cloud.githubusercontent.com/assets/26387044/25232932/aabd208a-25a2-11e7-8b40-58ed7e33ad9b.png)

**Comment by sagarjagdish** [comment]
added to Mail Code box

![image](https://cloud.githubusercontent.com/assets/7322922/25290055/d9c4f1b2-26e9-11e7-95ae-67c0e9dfee98.png)

**Comment by kbt1** [comment]
fixed
