### ISSUE TITLE
Membership and Dues Discount Field

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#106]
Discount is not being deducted in dues processing under Due Amount:
![image](https://cloud.githubusercontent.com/assets/26387044/25054920/78a09ffe-2125-11e7-9066-35681829ccb4.png)
![image](https://cloud.githubusercontent.com/assets/26387044/25054938/a1a8e29e-2125-11e7-901d-c1ca863df767.png)

Looks correct in Membership
![image](https://cloud.githubusercontent.com/assets/26387044/25054909/64a2dac6-2125-11e7-9a4d-982be90d2660.png)

**Comment by sagarjagdish** [comment]
We have updated code to apply discount in dues screen over dues amount. Please verify and let us know if any other change required.

![image](https://cloud.githubusercontent.com/assets/7322922/25217393/54aca72a-25c4-11e7-92e4-7333e4b27d6b.png)

**Comment by kbt1** [comment]
works good.
