### ISSUE TITLE
Add Upload File Under Problem in Tech Call

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS_Clients#107]
Can we add the ability to upload files (pdf, jpg, gif) to Problems, in case the caller has an image to the problem.

![screen shot 2017-04-18 at 9 39 20 am](https://cloud.githubusercontent.com/assets/7178461/25142296/42cc9056-241b-11e7-8fa9-2276c7f5a8ef.png)

**Comment by sagarjagdish** [comment]
added function to upload files to Problems.
 
![image](https://cloud.githubusercontent.com/assets/7322922/25217470/b55d9d22-25c4-11e7-9a44-cbfe57e3bfc1.png)
