### ISSUE TITLE
Add Payment Type in Membership/Show in Due and Processing

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS_Clients#108]
For the monthly member, can we add a payment type dropdown, just like inside Due and Processing? And the selected payment type should reflect inside Due Processing so Karen doesn't have to select it every month.

![screen shot 2017-04-18 at 9 51 30 am](https://cloud.githubusercontent.com/assets/7178461/25142792/0630b968-241d-11e7-9da8-d4c6642e5e74.png)
![screen shot 2017-04-18 at 9 53 11 am](https://cloud.githubusercontent.com/assets/7178461/25142793/0641b10a-241d-11e7-90b1-58ad76708d27.png)

**Comment by sagarjagdish** [comment]
added function to select payment type from membership add/edit screen and same reflect in dues screen.

![image](https://cloud.githubusercontent.com/assets/7322922/25217715/9383fde4-25c5-11e7-976c-279b3f3b655d.png)

**Comment by omnitekinc** [comment]
Thanks Sagar,
When we update the database, can we add the payment type for monthly payment? They should be inside the "monthly payments spreadsheet - FOR STELLA.xlsx"
https://github.com/omnitekinc/AERA_MSS_Clients/issues/111

**Comment by kbt1** [comment]
Payment type should be in Prosis also.
I have a couple members that pay differently for their monthly payments.
![image](https://cloud.githubusercontent.com/assets/26387044/25296059/08271172-26ac-11e7-8599-785984b56bae.png)

**Comment by sagarjagdish** [comment]
Payment type should be in Prosis also.
=> added different payment type for Prosis Pro.

![image](https://cloud.githubusercontent.com/assets/7322922/25369985/4a1d9d48-29a5-11e7-955c-d41c0d98784e.png)

![image](https://cloud.githubusercontent.com/assets/7322922/25370005/63fcd13e-29a5-11e7-92a6-f4ae94a1ecae.png)

**Comment by kbt1** [comment]
looks good.
