### ISSUE TITLE
Due Processing Batch Transcation Number

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS_Clients#109]
Hi Sagar,
We have a situation in Due Processing where I would like to get your opinion on. 
Right now if you create a batch, you have to put in no. of the transaction and $ amount. It works great. But sometimes one of the payment doesn't go through, Karen will have to change the no. of the transaction and the total amount. Right now when you change no. of the transaction, it deletes the last one on the list by default. Here are my recommendations:
1) Either we keep the no. of the transaction, Karen can update the batch amount, and for the payment that didn't go through, Karen will put $0 and it will be Null and it won't update in the system. 
2) Add a delete option next to each transaction. Where Karen can delete the one that didn't go through and it would auto update the total number of transaction of the batch.

**Comment by sagarjagdish** [comment]
We have added delete option for dues transaction before post. Please refer below image. Please review and let us know if any other change required in this.

![image](https://cloud.githubusercontent.com/assets/7322922/25218004/d10c6db2-25c6-11e7-8092-8a7aab721153.png)

**Comment by omnitekinc** [comment]
@kbt1 @stevefox3781 
Karen & Steve, per our discussion last week, we've added a delete function on individual transaction under batch processing, you can delete the item if the payment didn't go through.
Stella

**Comment by kbt1** [comment]
the delete works good, it reduces the number of transactions, but doesnt reduce the total.
Will i need to edit the batch and change the total?
![image](https://cloud.githubusercontent.com/assets/26387044/25247719/4eb6c492-25d1-11e7-9a54-ea987142fecf.png)

**Comment by omnitekinc** [comment]
Karen, it shouldn't automatically update the batch total, you will have to update it manually to make sure it all adds up properly.

**Comment by kbt1** [comment]
perfect, works good.
