### ISSUE TITLE
Membership - Shipping Address

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#11]
We need to be able to see the shipping address when viewing a member so we can confirm it is accurate when on the phone.  Right now only the mailing address appears when you're viewing a member.  
Example:  Member #1920 has both, but I cannot see the shipping address unless I go into Edit.

**Comment by sagarjagdish** [comment]
now shipping address showing in view screen. please verify and confirm.

http://71.13.159.202/aeramms_stage/addnewmember.aspx?id=2880&mode=view&searchterm=

**Comment by amandagoyette** [comment]
Shipping address appears thanks!
