### ISSUE TITLE
Prosis Invoice

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#110]
Member #469, no fee is coming up for Prosis but its in the record for $459?

![image](https://cloud.githubusercontent.com/assets/26387044/25233139/619d6ddc-25a3-11e7-85c0-afffa8eee652.png)

**Comment by sagarjagdish** [comment]
We have resolved this issue and uploaded on stage. please verify and confirm.

**Comment by kbt1** [comment]
good to go
