### ISSUE TITLE
Dues Report - Monthly Payments

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#111]
Stella
Is there a way you can duplicate this report in Dues Processing for me for monthly payments? (spreadsheet attached - minus my comments)
[monthly payments spreadsheet - FOR STELLA.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/943876/monthly.payments.spreadsheet.-.FOR.STELLA.xlsx)
Somehow I will need to know when the membership and prosis expires and due to renew after the year of monthly payments because I have to go into the charging or checking system and update dollar amounts that need to be processed per member if there are increases BEFORE I enter payments into Dues Processing.

Will you be able to mark all the monthly payment records in membership or will I have to go in and mark them?

Also, I do not want Monthly Payment members to get any invoices for dues or prosis pulled when i print or email them. Only Annual or 6 month renewals get invoiced. Instead, when monthly payment members 
1 year of payments is up, we would like to email or mail a monthly payment auto renewal letter 1 month before they expire. (sample letter attached - may be revised)
[Monthly Payment Auto Renew Letter.docx](https://github.com/omnitekinc/AERA_MSS_Clients/files/943881/Monthly.Payment.Auto.Renew.Letter.docx)

call me if you have any questions.

**Comment by omnitekinc** [comment]
Hi Sagar,
Can we add an export function under due processing for monthly payments? 
The report should look like the "monthly paymnets spreadsheet - FOR STELLA.xlx", sheet 2. Just 1 sheet not multiple sheets.
Thanks,
Stella

![screen shot 2017-04-20 at 10 53 59 am](https://cloud.githubusercontent.com/assets/7178461/25245836/ac9a5f72-25ba-11e7-98af-2b74ddf00ea7.png)

**Comment by sagarjagdish** [comment]
We have implemented this new report to export monthly payments. please review update on stage and let me know if there is any change required.

**Comment by kbt1** [comment]
Stella
The monthly payment report looks like it is missing a lot of records.
![image](https://cloud.githubusercontent.com/assets/26387044/25588487/18e14b44-2e6e-11e7-9903-80419a0f45f0.png)

Also, payment types are missing? Do i need to add those?
Can you separate the credit card payments and the check payments and total the columns?
here is the most current spreadsheet.
[2015 to 2016 monthly payments spreadsheet - for Stella 050117.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/968421/2015.to.2016.monthly.payments.spreadsheet.-.for.Stella.050117.xlsx)

**Comment by omnitekinc** [comment]
thanks Karen, will look into it.

**Comment by kbt1** [comment]
emailed Stella spreadsheet of Membership and Prosis monthly payment history we have in Quickbooks.

**Comment by sagarjagdish** [comment]
@omnitekinc  : Please provide me that history so I load into stage database to review.

**Comment by kbt1** [comment]
[Monthly Dues and Prosis Sales History.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/976205/Monthly.Dues.and.Prosis.Sales.History.xlsx)

here is the spreadsheet of payments. it is sorted by Member ID# and includes membership and prosis monthly payments.

**Comment by omnitekinc** [comment]
Sagar, once we've updated the data, let's look into adding the monthly payment info into member accounts.

**Comment by sagarjagdish** [comment]
@omnitekinc : We did review and need few more information in excel file to load data into AERA MMS new website. Please find attached file, I added few new column where we need data to load into current new database.

[Monthly.Dues.and.Prosis.Sales.History.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/986488/Monthly.Dues.and.Prosis.Sales.History.xlsx)

**Comment by kbt1** [comment]
i am going to have to work on this. i will get back with you.

**Comment by kbt1** [comment]
[Monthly Payment Sales History - Report 2.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/993846/Monthly.Payment.Sales.History.-.Report.2.xlsx)
Stella
Attached are the monthly payment transactions.
See if you can work with this.  Dont have it effect any expiration dates at this point.
Let me know if this will work.

**Comment by sagarjagdish** [comment]
I have looked into file and it's almost proper we just need start date and end date per record. see below for the example.

Excel Date :
![image](https://cloud.githubusercontent.com/assets/7322922/26051967/a022928e-3981-11e7-8cc0-63c7a2467de1.png)

Here we can see 05/22/2015 as payment date but this payment for which start date and end date. I think it's from 06/01/2015 to 07/01/2015.

![image](https://cloud.githubusercontent.com/assets/7322922/26052060/e27edc28-3981-11e7-9a17-d5a3c6850084.png)

Start Date and End Date used in report generate process. So please provide us Start Date & End Date for each record in same excel as I shown above.

Once we have Start Date & End Date it will resolved https://github.com/omnitekinc/AERA_MSS_Clients/issues/122 issue as well.

**Comment by kbt1** [comment]
Basically if the payment date is 5/22/2015 then the start date is 6/1/15 and end date is 7/1/15.
Is there any way you can calculate this on the spreadsheet?

I would have to manually enter every date on the spreadsheet because this is a new way of doing things.
If you cant do it, then just make sure all monthly payment companies are marked monthly payment with their payment type and I will keep my spreadsheet that I use and moving forward we will collect new data.

**Comment by sagarjagdish** [comment]
@kbt1 : We can do that for you and update start date and end date from our end however need confirmation on below.

I have notice few record in excel file having payment date is near to start date of the month like 07/09/2013, see below image.  So my question is what was the end date for such payment date. It should be **8/1/2013 and 9/1/2013** or **7/1/2013 and 8/1/2013**

![image](https://cloud.githubusercontent.com/assets/7322922/26089626/ee70552a-3a1c-11e7-859a-1a7a07932cbf.png)

**Comment by kbt1** [comment]
8/1/13-9/1/13

**Comment by sagarjagdish** [comment]
@kbt1 : We have uploaded record into current system with batch prefix "Auto Entry". We have added total 53 batch.

![image](https://cloud.githubusercontent.com/assets/7322922/26196680/4fdef6ce-3bdd-11e7-8003-3464f5c1e1b7.png)

After this action we exported monthly payment report and found almost same compare to "2015 to 2016 monthly payments spreadsheet - for Stella 050117.xlsx" file. I have on question like we received $71.5 payment of member 118 in April but this payment is for 05/01/2017 to 06/01/2017, so where we list that $71.5 inside April or May month.  Currently it's listed under May month as it's payment for May month. see below image.

**2015 to 2016 monthly payments spreadsheet - for Stella 050117.xlsx**
![image](https://cloud.githubusercontent.com/assets/7322922/26197229/1d218a42-3bdf-11e7-818c-14605104a668.png)

**New exported file**
![image](https://cloud.githubusercontent.com/assets/7322922/26197291/505587c4-3bdf-11e7-9c66-459a68bf81e6.png)

**Comment by kbt1** [comment]
I am going to start entering monthly payments in June.
I process the final monthly payments on May 23rd. Do you want me to send you all of may payments next week on a spreadsheet so you can enter the payments.

**Comment by sagarjagdish** [comment]
+++++++++++++++++++++++
I am going to start entering monthly payments in June.
I process the final monthly payments on May 23rd. Do you want me to send you all of may payments next week on a spreadsheet so you can enter the payments.
+++++++++++++++++++++++
Yes, you can provide me that file as well. I will do that from my end.

**can you please provide you comment on below?**
+++++++++++++++++++++++
After this action we exported monthly payment report and found almost same compare to "2015 to 2016 monthly payments spreadsheet - for Stella 050117.xlsx" file. I have on question like we received $71.5 payment of member 118 in April but this payment is for 05/01/2017 to 06/01/2017, so where we list that $71.5 inside April or May month. Currently it's listed under May month as it's payment for May month. see below image.

**2015 to 2016 monthly payments spreadsheet - for Stella 050117.xlsx**
![image](https://cloud.githubusercontent.com/assets/7322922/26197229/1d218a42-3bdf-11e7-818c-14605104a668.png)

**New exported file**
![image](https://cloud.githubusercontent.com/assets/7322922/26197291/505587c4-3bdf-11e7-9c66-459a68bf81e6.png)
+++++++++++++++++++++++

**Comment by kbt1** [comment]
This looks better. 
I think this will all work itself out once I start entering monthly payments in the new system for June which will be July payments.
I will send May payments processed for June at the end of the month after i process them all so you can get the system updated.

Thank you! I am leaving this open to remind me to send monthly payments.
