### ISSUE TITLE
Printing Invoices

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#112]
Wondering if for all US members, when we print an invoice, it doesnt print the country.
If you get mail, it does not have USA at the bottom of the address. It doesnt look right to me.
What do you think?
![image](https://cloud.githubusercontent.com/assets/26387044/25291015/f4b49242-2695-11e7-8cee-578a2a6aee57.png)

**Comment by sagarjagdish** [comment]
@omnitekinc  : Should we remove USA at bottom of the address?

**Comment by omnitekinc** [comment]
Yes, please remove USA, and only put country if it's not USA.

**Comment by sagarjagdish** [comment]
Removed USA from the bottom of the address and uploaded on stage.

**Comment by kbt1** [comment]
looks good
