### ISSUE TITLE
Session time out

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#113]
i thought there would be no Session Time Outs.

![image](https://cloud.githubusercontent.com/assets/26387044/25353540/3e4b0c7c-28f5-11e7-9d0b-30d25d70f736.png)

I was editing a dues batch. Got the error and click ok, nothing happens.
had to close and log back in.

**Comment by sagarjagdish** [comment]
We have not found any issue with screen and session. There is only one possibility like on 25th I did on upload on stage and during this upload this action was performed.

Please try with same process again. I hope this will be no issue.

**Comment by omnitekinc** [comment]
Karen, let's keep an eye on this. If it happens again please let us know.

Sagar, so as of right now the system will not log out any account automatically, correct?

**Comment by kbt1** [comment]
it logged me out today. 
I will let you know if its an on going issue.

**Comment by omnitekinc** [comment]
Sagar, can you make sure the system never log out for the users?

**Comment by sagarjagdish** [comment]
We have changed logic and not session will never log out until click on logout button. Please verify and confirm.

**Comment by sagarjagdish** [comment]
We have changed logic for the session time out and uploaded on stage. now session will never logout until user click on Log out button. Please verify and confirm.
