### ISSUE TITLE
Product Order Form

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#117]
This works great.  Just one question, the email comes from info@aera.org.
Can we have it come from staff email that sends it to me? It would be helpful to know who it comes from.
I didnt know if this would be the case or not once all the live data was in the system.

**Comment by sagarjagdish** [comment]
It's possible but for that we need to store credential information for all email address which we need to use to send email and it's not proper way. We have implemented like mask user name over "info@aera.org" email address and set email address of that user in replyto. So member who received product invoice can see something like below 

![image](https://cloud.githubusercontent.com/assets/7322922/25575809/ddf28444-2e77-11e7-91ab-9bd513c33633.png)

and when member click on reply it will show email address of sender which AERA specified in email/reply to text box.

![image](https://cloud.githubusercontent.com/assets/7322922/25575844/160bc89a-2e78-11e7-8c03-34d50a10ba27.png)

Please let me know, this will work or not?

**Comment by kbt1** [comment]
that should work.
it would just be nice to know who it came from on staff other then info@aera.org.

**Comment by omnitekinc** [comment]
Sagar, when AERA create an order form, can we put in the person's name based on their system login? That way, Karen can find out who created the order.

**Comment by sagarjagdish** [comment]
@omnitekinc : We have already shown person name as sender name in email, please read my previous comment. 

however please let me know if we need to show same name on any other places. Please suggest place, where you would like to show person name in email.

**Comment by kbt1** [comment]
good to go.
