### ISSUE TITLE
Log in

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#118]
Somehow my log in was reverted to the old system username: AP I want this updated to my current initials of AH again please.  Must have reverted when you updated the information so we can test reports.

Thanks!

**Comment by sagarjagdish** [comment]
@aharmening : I have updated user name with AP and password remain same. Please try to do login with AP.

**Comment by amandagoyette** [comment]
No, it's supposed to be AH.

**Comment by sagarjagdish** [comment]
@aharmening  : When I go for change it's already AH so I was changed that to AP :) 

I have again set it back to AH.

We can update that login initial from below screen.

http://71.13.159.202/aeramms_stage/systemsetting.aspx

**Comment by amandagoyette** [comment]
strange, it must have changed or got changed along the way!  It's correct now.  Thanks!
