### ISSUE TITLE
Membership-Product Invoice

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#12]
When I click the Product Invoice button it opens the membership/PROSIS renewal form instead of a form to create an order for product.

**Comment by omnitekinc** [comment]
We need to create a new window for Karen type in the product items for the invoice. Karen, can you please send me a sample of an invoice for store?
http://www.aera.org/store/c2/Shop_Supplies.html

**Comment by kbt1** [comment]
this is how I would like to see the order form look like
[Order form.docx](https://github.com/omnitekinc/AERA_MSS_Clients/files/851448/Order.form.docx)

**Comment by amandagoyette** [comment]
Stella, let us know if you need anything else after you look at the order form Karen included.  I think her template looks good.  We need to make sure if there is a different shipping address is pulls that over the mailing address too.

**Comment by omnitekinc** [comment]
Thanks Karen!
Amanda, I am going to mock up a screen based on this info and will share it here. 
Stella

**Comment by omnitekinc** [comment]
Hi Karen,
I have mocked up the invoice screen, can you please take a look and let me know if this would work?
Stella
[ShopInvoice.pdf](https://github.com/omnitekinc/AERA_MSS_Clients/files/869636/ShopInvoice.pdf)

**Comment by kbt1** [comment]
The form needs company info at the top of the page and it needs to be able to email or print
This is internal for me or any staff taking an order over the phone. 

ID#
Contact Name
Company Name		(all this company info pulls from membership record selected)
Address
City, State Zip Code
Country

**Comment by sagarjagdish** [comment]
@kbt1  : Is it required to keep history of all those generate/emailed product invoice per member#? It will help to track past product invoice with full detail.

**Comment by kbt1** [comment]
This is a generic form for us to be able to use when someone calls for an order or renewing a fee.
All our detail information is in our accounting software.
But it would be nice to see history of orders taken per member.

**Comment by omnitekinc** [comment]
Hi Sagar, I discussed this with the client and we have come up with a solution, I will share this on basecamp with you.

**Comment by sagarjagdish** [comment]
this implementation done now working with suggestion related to prosis pro / membership checkbox under https://github.com/omnitekinc/AERA_MSS_Clients/issues/81
