### ISSUE TITLE
Membership - Edit

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#120]
I need to show up as Amanda Harmening when editing, not Amanda Potter.  Like the user name I'm unsure why this reverted, but that was my maiden name and I don't want to be using it:
![image](https://cloud.githubusercontent.com/assets/26386841/25635341/65970872-2f43-11e7-9bc3-231ce2e932b2.png)

**Comment by sagarjagdish** [comment]
I have updated name as suggested. Please verify and confirm.

**Comment by amandagoyette** [comment]
good to go. Thanks!
