### ISSUE TITLE
Membership - Additional Contact

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#121]
when adding an email into the additional contact field it will not save the information without at least a first name.  Member #27208 I was trying to split the email addresses that were listed as the primary with a semicolon in between and I don't have a name for the workshop email.  It didn't save the info when I when to hit save nor did it warn me it wasn't going to.  I had to enter Workshop as the first name to get it to stick.

**Comment by sagarjagdish** [comment]
We did this change and uploaded on stage. Please verify this function and let me know if any other change required.

**Comment by amandagoyette** [comment]
good to go.  Thanks!
