### ISSUE TITLE
Monthly Reports Tab

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#122]
Stella

Just need to correct a couple report names:

Membership and Prosis Pro Comparison Report (remove - website)
Active Member Locator (add -website)
Associate Mailing List - remove Associate and just make Mailing List

The Membership and Prosis Pro comparison report does not look right as far as numbers go. (see attached comparison reports i just ran)
[Karen  PROSIS Comparison by Month - current for Stella.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/971809/Karen.PROSIS.Comparison.by.Month.-.current.for.Stella.xlsx)
[Karen Membership Comparison by Month -current for Stella.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/971810/Karen.Membership.Comparison.by.Month.-current.for.Stella.xlsx)

I checked some of the other reports and they seem pretty close.

**Comment by sagarjagdish** [comment]
+++++++++++
Membership and Prosis Pro Comparison Report (remove - website)
Active Member Locator (add -website)
Associate Mailing List - remove Associate and just make Mailing List
+++++++++++
=> changed label as suggested above and uploaded on stage.

+++++++++++
The Membership and Prosis Pro comparison report does not look right as far as numbers go. (see attached comparison reports i just ran)
Karen PROSIS Comparison by Month - current for Stella.xlsx
Karen Membership Comparison by Month -current for Stella.xlsx
+++++++++++
=> We did verification but not found anything wrong with the data. I have attached our comment with SQL query which we used to export data. We can't find any issue. Please let us know your view and verify once.

[comparison-report-review-05-09-2017.docx](https://github.com/omnitekinc/AERA_MSS_Clients/files/986504/comparison-report-review-05-09-2017.docx)

**Comment by kbt1** [comment]
Stella:
I am checking the Monthly reports tab:
Email blast report is good
Expired monthly call report is good

Membership and Prosis Monthly comparison reports:
membership seems a little too off. See my comparisons of new and old.
prosis is pretty close, my counts from old system might include trials so thats ok. But i have highlighted what we need added in. I need Prosis Pro Web, Prosis Pro Desktop, and Prosis Pro web and desktop counts.  
[ProsisProComparisonReport - new and old.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/997091/ProsisProComparisonReport.-.new.and.old.xlsx)
[Membership Monthly Comparison Report - new and old system.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/997092/Membership.Monthly.Comparison.Report.-.new.and.old.system.xlsx)

**Comment by omnitekinc** [comment]
Thanks Karen, we will look into it.

Sagar, can you please take a look and see why the numbers don't seem to match Karen's excel?

**Comment by kbt1** [comment]
I ran Membership Comparison Report today and these are the results, i thought maybe data was wrong but its been updated so i am not sure.

![image](https://cloud.githubusercontent.com/assets/26387044/26126105/0272c6a2-3a4a-11e7-82e6-7c0dbfd2bfb7.png)

**Comment by sagarjagdish** [comment]
@kbt1 : We will recheck once we load your provided excel file https://github.com/omnitekinc/AERA_MSS_Clients/issues/111 in database.

There is many dues transaction missing in AERA membership database which should be there. I will update to once https://github.com/omnitekinc/AERA_MSS_Clients/issues/111 is done.

**Comment by sagarjagdish** [comment]
We have added monthly dues record on new system as per https://github.com/omnitekinc/AERA_MSS_Clients/issues/111 and export report. however found difference.

see below image.

![image](https://cloud.githubusercontent.com/assets/7322922/26200176/837e1782-3bea-11e7-8ddb-53a1b097e334.png)

It's only because we still have 82 member active in May-2017 but not exist in dues transaction. see attached file.
[dues_transaction_not_found.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1010665/dues_transaction_not_found.xlsx)

another reason like we restore membership database before few days so some of the member update in old system which not be updated here with dues transaction.

**Comment by kbt1** [comment]
Membership and Prosis counts should be calculated by Expiration date, not dues payments.
I am keeping old system and new system updated together.
