### ISSUE TITLE
Membership Date Range filter

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS_Clients#123]
Sagar, can we change the date range filter. AERA don't need to search by date range. Start Date is fine, leave it as is. End Date should change to Expiration Date, and AERA will select ex. 05/01/2017, and it will only show all members expired on that exact date. 

![screen shot 2017-05-03 at 10 12 24 am](https://cloud.githubusercontent.com/assets/7178461/25672589/0be140b2-2fe9-11e7-8d4d-b82235d6fd29.png)

**Comment by sagarjagdish** [comment]
Updated logic for the Start Date and End Date. We rename End Date with "Expiration Date". when AERA select expiration date will show only those record which having exact expired date.

There is no change in logic of Start Date and it's working as it before.

**Comment by omnitekinc** [comment]
Amanda, please check for this update.

**Comment by amandagoyette** [comment]
Looks good. Thanks!
