### ISSUE TITLE
Test Line Text - TEST TYPE

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#124]
be sure to delete this from the system.

**Comment by omnitekinc** [comment]
Karen, can you please provide a screen shot.

**Comment by kbt1** [comment]
its a member class in Monthly report eblast area, i think it was for testing purposes

![image](https://cloud.githubusercontent.com/assets/26387044/25714715/82e1e4a2-30be-11e7-9572-e1f6150a549d.png)

**Comment by sagarjagdish** [comment]
Removed that class. actually we have added that class for testing. 

We have function to add and remove class from "System Setting >> Pricing".

**Comment by kbt1** [comment]
gone.
