### ISSUE TITLE
Tech Que Reports

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS_Clients#125]
Need to make sure for the options that currently don't have the data, uncheck them.

**Comment by sagarjagdish** [comment]
@omnitekinc : We updated logic like no need to un-check anything as it's selected all so it will export all from the system.

Also we changes label for date range from "All" to "Get Last One Year Tech Queue". If we going to generate report without date selection then system taking tool long time to generate report as there is too many record in tech call. so changes it from "All" to "Get Last One Year Tech Queue".

[TechQueue-05-05-2017.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/978778/TechQueue-05-05-2017.xlsx)

**Comment by omnitekinc** [comment]
steve, can you please take a look at the report?

**Comment by stevefox3781** [comment]
Looks good to me.
