### ISSUE TITLE
Product Order Form

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#126]
Is it possible to make the screen longer so you don't have to scroll down to finish filling in the form?

**Comment by sagarjagdish** [comment]
@omnitekinc : I think we can create new screen (new page) instead of overlay window to resolve this issue. actually product page already large enough for the page.

**Comment by sagarjagdish** [comment]
@omnitekinc : Please see my above comment and let me know which action required.

**Comment by amandagoyette** [comment]
Not sure if my computer had issues that day, or if you made a tweak, but I think we're good.
