### ISSUE TITLE
Membership and Prosis record error

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#128]
I updated both these to monthly payments on Friday morning. ID#17380
Prosis is current and Membership is not.
Are you sure you pulled the correct data?

![image](https://cloud.githubusercontent.com/assets/26387044/25863652/3b1a0828-34b2-11e7-80cb-6ad8fef029ab.png)

**Comment by omnitekinc** [comment]
Hi Sagar,
Can you verify the version of data you pull? And check and see why this update wasn't reflected.
Thanks!
Stella

**Comment by kbt1** [comment]
Stella and Sagar
Please let me know immediately if you have to do a new data pull.
I have a lot of new members and dues and prosis renewals to enter and I am going to use both systems so I need them to match.

Thank you!

**Comment by sagarjagdish** [comment]
@kbt1 : I have pulled membership database on 30th APR 2017 and updated same (30th APR 2017) on web. 

Today I just updated Prosis Database for the users and company so not Membership. 

If it's required to update Membership Database again then I will do this after your working hours.  Please let me know if any query.

**Comment by omnitekinc** [comment]
@sagarjagdish: Yes please update the database tonight so we will have the latest data on the staging system.

**Comment by sagarjagdish** [comment]
@omnitekinc : Sure I will do this by tonight.

**Comment by kbt1** [comment]
can you update both membership and prosis so data is pulled on the same day?
i will get everything updated today so you have all updated data tonight.

**Comment by sagarjagdish** [comment]
@kbt1 : Okay. got that. I will update Prosis and Membership both database by tonight.

**Comment by kbt1** [comment]
Just curious if Membership and Prosis were both updated yet?
I double checked expired members for May 1 and there are several on the first page that come up expired and they are paid.  I check marked just a few that are paid.
![image](https://cloud.githubusercontent.com/assets/26387044/25906423/3560e556-356a-11e7-8a65-dbcafb5caf63.png)
 I was hoping to run new invoices this week and test it out.
Let me know.

**Comment by omnitekinc** [comment]
Karen, we couldn't get into the server last night to pull the data, we might need to talk to VCS

**Comment by amandagoyette** [comment]
Please let me know who VCS should contact and a good phone number to reach them at and I'll get the conversation started

**Comment by kbt1** [comment]
Stella
Please let me know when you are doing the data pull, probably best to do it end of day.
Thanks!

**Comment by omnitekinc** [comment]
Amanda, I sent you an email this morning with screen shots, I think once VCS see the screenshots they will know what to do.

**Comment by amandagoyette** [comment]
Steve just called me and let me know the computer was off last night.  Please try again tonight.  You should be good as he turned it on today.

**Comment by omnitekinc** [comment]
Thanks Amanda, will do that tonight.

**Comment by sagarjagdish** [comment]
We have updated AERA Membership & Prosis database by yesterday.

**Comment by kbt1** [comment]
looks good
