### ISSUE TITLE
Assigned Name Changes

### ISSUE THREAD

**Issue by robchar** [omnitekinc/AERA_MSS_Clients#13]
In the drop down box for assigned users lists Mike Caruso and Yolanda Carranza, they are no longer with AERA. Please add Rob Munro to the assigned list.

**Comment by sagarjagdish** [comment]
I notice some one removed that user from the system. We are showing employee list by referring below Admins screen. If you want to remove or Inactive any user then it's possible by using that screen.

System Settings >> Admins
http://71.13.159.202/aeramms_stage/systemsetting.aspx

Please let me know if there is any query/issue with this function.

**Comment by stevefox3781** [comment]
The are Rob is refering to is shown in the screen shot by the red box. We need to add his name and remove the following names: Amanda, Jim, Karen & Mary. Also if you can put a space between the first and last name it would make it look better. Rob is added to admin side, but the name is not showing up. 

![tech name added](https://cloud.githubusercontent.com/assets/26387391/24202848/11ca0310-0ee2-11e7-9955-58701f87ffa3.jpg)

**Comment by sagarjagdish** [comment]
We are showing only those under in that list who having Full access on Queue. Please see below screen. I have updated Rob users with Full access and now it's start showing.

![image](https://cloud.githubusercontent.com/assets/7322922/24500749/4b3f50cc-1564-11e7-8c9b-d87bcc5cfa84.png)

![image](https://cloud.githubusercontent.com/assets/7322922/24500801/8699128e-1564-11e7-806b-c5c6e4fd5e43.png)

**Comment by stevefox3781** [comment]
OK. Thank you!
