### ISSUE TITLE
Closed Calls

### ISSUE THREAD

**Issue by stevefox3781** [omnitekinc/AERA_MSS_Clients#131]
When I click on the Closed Calls tab in the tech center, the recent calls are going to the last page. I done 3 calls today 5/11/2017 and they were on the last page of the report - page 14057. It looks like the close date and time are not getting filled in when the call is closed. 

![closed calls](https://cloud.githubusercontent.com/assets/26387391/25960465/9faa9e02-363c-11e7-9a15-2d1acee0873d.jpg)

**Comment by sagarjagdish** [comment]
I have looked into this issue and found cause. There is issue with edit tech call and close process. 

We have resolved this issue and uploaded on stage. Please verify and confirm.

**Comment by stevefox3781** [comment]
Works!
