### ISSUE TITLE
Dues Batch

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#132]
Stella
Other then the monthly payments, can you default the payment method to empty until i enter something?
if not, no worries.
Before anything is entered, the Payment Method box says ACH, then when i enter an ID# it comes up check, it would be easier if it came up empty so I dont mess up a payment type.

![image](https://cloud.githubusercontent.com/assets/26387044/25967239/1a02dfe6-3653-11e7-950d-e1f2c96784cd.png)

**Comment by sagarjagdish** [comment]
We have taken action as suggested please take look and let us know if any issue.

**Comment by kbt1** [comment]
good to go
