### ISSUE TITLE
Dues Batch

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#133]
Member #2236 for Prosis payment is coming up Outside US Price in dues processing.
They are inside the US. Not sure where the system is pulling this?

![image](https://cloud.githubusercontent.com/assets/26387044/25968604/c10d707c-3657-11e7-8064-655e55d9e9ac.png)

In the Membership record, the price is correct but the Prosis Pro Account is marked at Single Outside US but has Inside US price.

![image](https://cloud.githubusercontent.com/assets/26387044/25968744/392661a4-3658-11e7-8be1-8e9da69cf534.png)

**Comment by sagarjagdish** [comment]
I have looked into code for the logic and found mistake. We have resolved this issue and now it's showing proper. Please verify and confirm.

**Comment by kbt1** [comment]
good
