### ISSUE TITLE
PROSIS PRO Account Type

### ISSUE THREAD

**Issue by stevefox3781** [omnitekinc/AERA_MSS_Clients#134]
I have included a spreadsheet that has some highligthed PROSIS PRO users. If you look at the PROSIS Account Type column, the highlighted ones are coming up OUTSIDE US, which in turn, they are located in the US. The price seems to be correct, but the account type is not. Needs to be switched to US. Any questions, let us know. 

[PROSIS PRO Report.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/994296/PROSIS.PRO.Report.xlsx)

**Comment by sagarjagdish** [comment]
We have updated all the users by using your provided file. Please verify and confirm.

**Comment by kbt1** [comment]
Steve, I checked and they seem to be coming up correctly. if you want to run your report again and double check and close issue

**Comment by stevefox3781** [comment]
All good.
