### ISSUE TITLE
Dues processing

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#137]
I am processing an expired member that is reinstating their membership and their dues amount is coming up wrong.
not sure why.

![image](https://cloud.githubusercontent.com/assets/26387044/26014809/d6437622-3723-11e7-9076-e263a477c524.png)
It should be $439, i dont know where $394 is coming from.

I am entering a renewal for June 1 and their fee should be $399 and its coming up $392 due.
![image](https://cloud.githubusercontent.com/assets/26387044/26014894/339ab646-3724-11e7-9c4b-ebdc1d844f39.png)

**Comment by sagarjagdish** [comment]
We have resolved this issue and uploaded on stage. Please verify and confirm.

**Comment by kbt1** [comment]
looks like amounts are coming up correct in dues.
