### ISSUE TITLE
I need this Member#43048 added to new system

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#139]
They are a member of New Zealand Association and are not in the membership system but they are in CMS.  I need them added to the new system so I can process their Prosis renewal.

![image](https://cloud.githubusercontent.com/assets/26387044/26079818/bcd8d6ec-3989-11e7-997f-04d66a5675ef.png)
![image](https://cloud.githubusercontent.com/assets/26387044/26079848/d70ce6d4-3989-11e7-8cb9-3e22aab6cd5c.png)

**Comment by sagarjagdish** [comment]
Now such member shows up in new AERA Membership system. Please refer below URL to lookup.

http://71.13.159.202/aeramms_stage/membership.aspx?searchterm=43048&search=return&Opentab=tab-1-contant

Please review member detail and let me know if any change required in this.

**Comment by kbt1** [comment]
perfect, thank you.
