### ISSUE TITLE
Emailing from Tech Call

### ISSUE THREAD

**Issue by stevefox3781** [omnitekinc/AERA_MSS_Clients#141]
The email that is sent to member comes from "info@aera.org", can we change that to "tech@aera.org". This is when we are emailing a pdf file to member.

**Comment by sagarjagdish** [comment]
Uploaded this change please refer below image.

![image](https://cloud.githubusercontent.com/assets/7322922/26199456/acd1979c-3be7-11e7-8264-0b7cfb829907.png)

**Comment by stevefox3781** [comment]
Great!!!

Thank you
