### ISSUE TITLE
ID#15017 expired member

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#142]
they never joined. can you remove the join date and move to prospect tab

![image](https://cloud.githubusercontent.com/assets/26387044/26120616/f5622272-3a36-11e7-81fa-9d2f598e38bc.png)

**Comment by omnitekinc** [comment]
@sagarjagdish there's going to be a small group of the user who is not members but is using Prosis Pro, and this is one of the examples. Maybe we need a category that's nonmember who uses Prosis?

**Comment by kbt1** [comment]
this company is not a prosis pro user either.

**Comment by sagarjagdish** [comment]
@omnitekinc : I have checked and not found any Prosis Pro user who is not members. so I think that is not the issue.

@kbt1 : We moved that user under prospect tab. Please refer below image. 

![image](https://cloud.githubusercontent.com/assets/7322922/26200587/727e0fc6-3bec-11e7-9848-24a8279e9f3c.png)

**Comment by kbt1** [comment]
ok
