### ISSUE TITLE
Prosis 30 Day Trial Record

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#144]
this member looks like they paid for a year with a start date of 5/11/16 and expiration date of 5/11/17 but they are a demo. there should not be a start date unless the start date should be 4/11/17.
Do I manually change this??

![image](https://cloud.githubusercontent.com/assets/26387044/26154289/83d2b72c-3ad4-11e7-9a7e-764f77698374.png)

**Comment by sagarjagdish** [comment]
@kbt1 : I will look into this. I think there is issue with update prosis data with our script. Where we need to ignore demo user for the start date and exp date for prosis pro.

We will update this from every where using script.

You can change it manually as well.

**Comment by sagarjagdish** [comment]
We have updated all demo users with one month past start date instead of one year. Please verify and confirm.

![image](https://cloud.githubusercontent.com/assets/7322922/26198391/7a2f07a6-3be3-11e7-9cb4-6afd46db9ed5.png)

**Comment by kbt1** [comment]
looks good.
