### ISSUE TITLE
Tech Call Assign to different user notification

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS_Clients#145]
Sagar, can we send an email notification when a Tech Call has been assign to a different AERA tech?

**Comment by sagarjagdish** [comment]
You means like need to send email when AERA tech changed, correct? We can do that.

**Comment by sagarjagdish** [comment]
@omnitekinc  : Please provide email body text which we need to send to AERA tech on assignment.

**Comment by sagarjagdish** [comment]
We have implemented this function and uploaded on stage. We need email body content to mark this work as done.

**Comment by omnitekinc** [comment]
Sagar, the email should be:
 If steve@aera.org assign a tech call to dave@aera.org
Email send to Dave.
Copy should be:
A tech call has been assigned to you by "steve@aera.org". 
Member ID#
Link to the call.

**Comment by sagarjagdish** [comment]
implemented this function with suggested body of content. please verify and confirm.

**Comment by omnitekinc** [comment]
@stevefox3781  Steve can you see if this is working for you.

**Comment by stevefox3781** [comment]
@omnitekinc - Stella I had Karen put a call in the tech queue and assign it to me at 11:40 and I have not received email as of 11:46

**Comment by omnitekinc** [comment]
Thanks @stevefox3781 , @sagarjagdish please look into it.

**Comment by sagarjagdish** [comment]
We need email address in below screen to send email to users.

![image](https://cloud.githubusercontent.com/assets/7322922/26398872/927f37ea-4098-11e7-823d-e6273d28b9da.png)

**Comment by stevefox3781** [comment]
Emails have been added.

**Comment by kbt1** [comment]
I added a call and assigned it to Dave Hagen and he did not get an email notification.
I think how it should work is if a new call is assigned to someone, they should get an email notification and who it was from. Or if someone reassigns a call to a tech, they should get notified and who it was from.

**Comment by omnitekinc** [comment]
@sagarjagdish Please test this. Also, we need the ability to send the notification for a new call, a notification should be sent as the call is saved.

**Comment by sagarjagdish** [comment]
I have looked into this and notice there is no issue with email send function just check Spam folder. It's sending email to Spam. There is issue with HTML which we added for this email. I have updated HTML and now it should work proper. 

Please verify and let me know if any issue. If you received email in Spam folder Just makes as "Not Spam" to get inside inbox. It's only one time activity.

**Comment by kbt1** [comment]
tested and works.
