### ISSUE TITLE
Prosis Pro Account info ID#44249

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#147]
I edit this members account and make payment type "Select" since they are a trial user

![image](https://cloud.githubusercontent.com/assets/26387044/26207294/bb60a996-3bac-11e7-938b-307af3ac303c.png)

after i save it, it seems to default to monthly.

![image](https://cloud.githubusercontent.com/assets/26387044/26207384/f5299ef8-3bac-11e7-8d29-dd2b6da12d03.png)

**Comment by sagarjagdish** [comment]
resolved this issue, actually there we wrote logic like if member is trial then auto set to monthly. now it's working fine as per requirement and I have updated that member as well.

Please refer below image.

![image](https://cloud.githubusercontent.com/assets/7322922/26251790/0fc9ac38-3ccc-11e7-8a52-9eae69a695f5.png)

**Comment by kbt1** [comment]
looks good now.
