### ISSUE TITLE
Being able to search the database

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#15]
Stella

We need an option on the membership screen to search for:
ID#
Company Name
Phone
Fox
Email

be able to enter one of the above and pull the record up.
this makes it easier so we dont have to pull the list and go through a list. 

see example below:
![image](https://cloud.githubusercontent.com/assets/26387044/24058566/85e75846-0b19-11e7-9402-57e94191c399.png)

**Comment by amandagoyette** [comment]
I have successfully tested the search box for id#, first name, last name, Company, phone, & Email.  Fax is the only one that doesn't work currently.

**Comment by kbt1** [comment]
Sorry, i totally missed the search box at the top.
