### ISSUE TITLE
Monthly Reports Tab

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#150]
New Member Report
7/1/16 to current
I have my spreadsheet and below is what i got out of the new system.
Since I cant change Join Date, this might effect the spreadsheet when i pull this info.
Can something be done???

[New membership worksheet comparison old vs new 051817.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1012423/New.membership.worksheet.comparison.old.vs.new.051817.xlsx)

**Comment by sagarjagdish** [comment]
Please find attached file for my findings. I have listed reason like why there is variation.
[Review FY17 for New membership worksheet comparison old vs new 051817.docx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1019263/Review.FY17.for.New.membership.worksheet.comparison.old.vs.new.051817.docx)

**Comment by omnitekinc** [comment]
@kbt1  Karen does Sagar's explanation make sense? Should we change the join date?

**Comment by kbt1** [comment]
Yes, i believe the join dates need to be changed so they show up on my spreadsheet.
If I report # of new members and then cant come up with a spreadsheet that matches, everyone will question me.
Can you change them or will you make the join date field so i can edit the dates?
If you change the dates, just make the join dates the first of the month from my spreadsheet.
So if they are under the December new member tab, make their join date December 1. 2016.
Our fiscal year is July 1 thru June 30th. So we are currently in July 2016 thru June 30, 2017 Fiscal year.

**Comment by omnitekinc** [comment]
@sagarjagdish Can we make the join date editable? And update the join date per Karen's instruction. 
thx!

**Comment by sagarjagdish** [comment]
@kbt1 : I have make the join date editable so you can now change the Join date.

If we take action as per your suggestion to change join date like put join date of member# 2689 to 08/01/2016 instead of 08/04/2016, it will still showing under Aug-16 which absent in your old report (see below image). Please confirm.

![image](https://cloud.githubusercontent.com/assets/7322922/26439843/6857b7bc-4147-11e7-885b-13ab277667a9.png)

**Comment by kbt1** [comment]
i will edit the join dates for the members missing from my old report and double check before i close this.

**Comment by kbt1** [comment]
looks good.
