### ISSUE TITLE
Prosis 

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#151]
Under Prosis Tab: is there anyway you can mark records Prosis Pro, Prosis Pro Desktop, or leave blank if they havent registered for either?

![image](https://cloud.githubusercontent.com/assets/26387044/26318972/c64aa184-3ee2-11e7-9371-f8b941e7cdde.png)

Like CMS so at a quick view, we know.
![image](https://cloud.githubusercontent.com/assets/26387044/26319014/f17a0cdc-3ee2-11e7-9193-eb598327d2e1.png)

**Comment by sagarjagdish** [comment]
shown marked records for Prosis Pro, Prosis Pro Desktop if user registered. Please refer below image.
 
![image](https://cloud.githubusercontent.com/assets/7322922/26349524/a16b7e10-3fcd-11e7-9320-82919f1ddb8f.png)

**Comment by kbt1** [comment]
looks good.
