### ISSUE TITLE
Current Members Tab

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#152]
I select a current member under the Current Members Tab,
then i use the < arrow to go back to current members tab
it brings me to Expired Members tab.

**can you have it default to current members?**

Current member tab
![image](https://cloud.githubusercontent.com/assets/26387044/26319227/c59129ce-3ee3-11e7-9222-42a9ffde8acf.png)

Select current member
![image](https://cloud.githubusercontent.com/assets/26387044/26319246/d8ab4f44-3ee3-11e7-8d56-c8837b9fa9c6.png)

click on < back arrow and brings me to expired members
![image](https://cloud.githubusercontent.com/assets/26387044/26319290/14813d3a-3ee4-11e7-9738-1b71907e82f7.png)

**Comment by sagarjagdish** [comment]
We have resolved this issue on stage. Please verify and confirm.

**Comment by kbt1** [comment]
works good.
