### ISSUE TITLE
Emailing a Membership and Prosis invoice

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#153]
I tried emailing an invoice and got this:

![image](https://cloud.githubusercontent.com/assets/26387044/26319832/362fd8b8-3ee6-11e7-84f6-7cc6b37c092e.png)

**Comment by sagarjagdish** [comment]
I have tried with my email to send invoice of same member and it's working. can you please confirm email address is proper or try again.

![image](https://cloud.githubusercontent.com/assets/7322922/26346261/4410c7fc-3fc3-11e7-8f8d-d5e73e068ba4.png)

**Comment by kbt1** [comment]
worked today, maybe there was a glitch in network when i had problem.
