### ISSUE TITLE
Prosis Pro - log user out

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#156]
Stella
we are still coming across members that log in and get the message " you are already logged in"
so they call and then we login into http://www.prosispro.com/admin/UpdateUserLogin.aspx
and then have to type their user name and log out user.

Can you add this function directly here so all we have to do is pull up the member and click on the Prosis Tab and then we can log them out there?
![image](https://cloud.githubusercontent.com/assets/26387044/26365964/e187f5ba-3fae-11e7-9dba-cf4ccb00ea73.png)

**Comment by sagarjagdish** [comment]
We have added logout button per Prosis Pro user in new Membership website.

![image](https://cloud.githubusercontent.com/assets/7322922/26396458/eba4fca4-4090-11e7-995a-e97da9d862dd.png)

**Comment by kbt1** [comment]
looks good. i will test it when i can and if there are problems, will let you know.
