### ISSUE TITLE
Membership and Prosis records marked Semi Annual

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#158]
Can you please update so all Semi Annual accounts whether membership or prosis are marked Annually instead. There are 37 records that have Semi Annual.

There should only be Annually and Monthly.

![image](https://cloud.githubusercontent.com/assets/26387044/26414059/913e2dd4-4073-11e7-9cd7-185eda54b080.png)

**Comment by sagarjagdish** [comment]
Now there is no more  Semi Annual member in system. We have updated on stage.

**Comment by kbt1** [comment]
good to go.
