### ISSUE TITLE
Regionals - Register for Conference - How Many People are Attending

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#16]
We need to either change the question to how many additional people are attending or fix the default as right now when you select 1 person is attending it requires a 2nd contact and wants to charge for 1 additional.

**Comment by omnitekinc** [comment]
Sagar,
Can you change the copy to "How many additional people are atendding?"
<img width="509" alt="screen shot 2017-03-18 at 11 46 32 am" src="https://cloud.githubusercontent.com/assets/7178461/24074996/904a1af0-0bd0-11e7-9429-6510b52f4cd7.png">

**Comment by sagarjagdish** [comment]
I have updated label with "How many additional people are attending?" as suggested by Stella. Please verify and confirm.

**Comment by amandagoyette** [comment]
looks good!
