### ISSUE TITLE
AERA Membership Certificate

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#160]
Stella
Something i had originally mentioned and forgot about. 
At the end of every month, I print membership certificates for Members that renew that month.
Its a word document that I used to merge using a query in the access database.
Basically, if I am printing this months members, I would put in an expiration date of 5/1/18 so it pulls all members with that expiration date.  Not to include Monthlys.
Its a preprinted form and this is what the document for merging looks like.
[AERA Member Certificate for Stella.docx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1026670/AERA.Member.Certificate.for.Stella.docx)

It pulls their Company Name which is bolded. City, State and Country if outside US. Join Date through Expiration Date.

Then I also need to be able to create labels with mailing information for each certificate to print in the same order as certificates on Avery 5160 Labels.

[copy of membershipcertificates and labels.pdf](https://github.com/omnitekinc/AERA_MSS_Clients/files/1026769/copy.of.membershipcertificates.and.labels.pdf)

**Comment by sagarjagdish** [comment]
I have question like we need to generate PDF format (colored well designed certificates) from the system or need to generate only doc format which provided in previous comment.

**Comment by kbt1** [comment]
generate the doc format so I can enter a month and print membership certificates for members that renewed that month. I have preprinted certificates that i use. I sent the pdf sample so you can see what the end result looks like.

**Comment by omnitekinc** [comment]
@kbt1 Hi Karen, just want to clarify:
1. you need to generate a word doc with all the members that's been renewed that month (I assume it will be annual members only). Each member will be on 1 page of the word doc that's formatted the same way you posted here. If you have 50 members renew, you will have a word doc with 50 pages. Correct?
2. Mailing label, do you have a format for these mailing label?

**Comment by kbt1** [comment]
Annual Members with Expiration date of 6/1/18 would be printed in June.
So if I have 150 Members that have the Expiration date of 6/1/18, then i will have 150 docs to print.

The mailing labels are Avery 5160 Labels.
Once again, If I have 150 Member Certificates to print, then i will have 150 labels to print.
I sent a sample of the labels. They are 30 labels to a sheet. 1"x 2 5/8"

**Comment by omnitekinc** [comment]
@sagarjagdish Hi Sagar, please let me know if you have any questions. Attached is the label template, we need to dynamically generate the word docs (for certificate) and generate address on the label. We can add a new function under Export and call it "Member Certificates" and have the option for Karen to select all the renewed annual member of that month. 

@kbt1 Karen, do you just print all the expired member of the month and send them out as the renew? 

[U-0087-01_P.doc.zip](https://github.com/omnitekinc/AERA_MSS_Clients/files/1029507/U-0087-01_P.doc.zip)

**Comment by kbt1** [comment]
yes. i print them as they renew. Usually if they dont renew in the current month, they renew down the line and their expiration date is changed so they would come up eventually in following months.

**Comment by sagarjagdish** [comment]
We have implemented function to export certificate in doc file and export label in PDF file. Please find below image. We have added this function under "Membership/Prosis Pro >> Monthly Report"

![image](https://cloud.githubusercontent.com/assets/7322922/26539274/2f78ad1e-4469-11e7-98c5-16629e447bd5.png)

**Comment by kbt1** [comment]
I have one more question, is there a way to implement entering an ID# instead of date and just print a certificate for a member that calls after the fact?

keep how you have it shown and then underneath, be able to enter ID# and it will bring up a certificate for that member ID#?

**Comment by kbt1** [comment]
Looks like the certificate prints good.
I printed 1 sheet of labels and it looks like there are 2 issues:
* in the 2nd column, Paul Marino, Marinos Automotive Machine Shop Inc prints onto the next label and so does Sue Dunn, Carter Machinery Co Inc.  Top margin needs to be adjusted for 5 lines of address.
* the 3rd column needs the left margin adjusted, printed too off the left side of the label.
see sample:
[sample of Export Mailing Labels for Certificates.pdf](https://github.com/omnitekinc/AERA_MSS_Clients/files/1039125/sample.of.Export.Mailing.Labels.for.Certificates.pdf)

**Comment by sagarjagdish** [comment]
We have uploaded fixes on stage. Please verify and let me know if it's work or not.

![image](https://cloud.githubusercontent.com/assets/7322922/26632893/3b426618-462f-11e7-9b16-7975ff4d0c33.png)

As possible as I set space between two columns, let me know if any issue with space.

![image](https://cloud.githubusercontent.com/assets/7322922/26632944/607bbc5e-462f-11e7-9cf8-188fbd73a65a.png)

**Comment by kbt1** [comment]
I have attached a set of labels and have circled the issues.
Looks the you need to adjust top margin for all and that should fix the 5 line addresses printing on 2 labels.
The 3rd Column is still printing wrong, need to adjust left margin.
[Certificate Labels.pdf](https://github.com/omnitekinc/AERA_MSS_Clients/files/1042646/Certificate.Labels.pdf)
Here is the exact template for the labels, this might help.
[Labels Template for Certificate Labels.docx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1042659/Labels.Template.for.Certificate.Labels.docx)

**Comment by sagarjagdish** [comment]
@kbt1 - I tried to make this issue resolved and uploaded changes. can you please verify once and let me know your feedback on this?

**Comment by kbt1** [comment]
Labels look good.
1 - can you adjust Font Size to 10
2 - can you make this merge into a word doc instead of a pdf so I can manually adjust longer company names or addresses?

**Comment by sagarjagdish** [comment]
1 - I tried and changed font size with 10 it's not showing proper result. Please see below.

Font size: 10px;
![image](https://user-images.githubusercontent.com/7322922/27131907-74ed891e-512a-11e7-9800-06ac5a684672.png)

Font size: 8.5px;
![image](https://user-images.githubusercontent.com/7322922/27131909-7772aa7a-512a-11e7-9c33-9e54366dcbf3.png)

2- I am trying to export same data in word but it will take more time for me to develop this logic.

**Comment by sagarjagdish** [comment]
2 - now Certificate Labels exported as doc file, so you can manage height from your end. We tried but we can not merge Certificate and label in single doc file as Certificate in landscape format and label in portiere.

However exported Certificate and label having same sequence, so no need to worry about the sequence event if both exported separately.

Please verify and let me know if any change required in this.

**Comment by kbt1** [comment]
this will work.
