### ISSUE TITLE
Monthly Reports

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#161]
Association should be Associate 

![image](https://cloud.githubusercontent.com/assets/26386841/26454949/3a1e3844-412e-11e7-8c70-c5faf13cfadf.png)

![image](https://cloud.githubusercontent.com/assets/26386841/26455085/c0d4770e-412e-11e7-8cf7-ee4782be5f7b.png)

**Comment by sagarjagdish** [comment]
We have resolved this typo on stage. Please verify and confirm.

**Comment by amandagoyette** [comment]
looks good thanks!
