### ISSUE TITLE
Prosis Pro Log User Out

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#162]
I got an opportunity to test the "Logout" function in the new system and it did not work but I went back to old way and it worked.
not sure why.
New system:
![image](https://cloud.githubusercontent.com/assets/26387044/26463683/bd4fd418-414a-11e7-8831-38b49f966be8.png)
![image](https://cloud.githubusercontent.com/assets/26387044/26463706/db82d106-414a-11e7-978f-381470c67020.png)

In CMS:
![image](https://cloud.githubusercontent.com/assets/26387044/26463739/f1cc5d4c-414a-11e7-96d2-b7c7dd3488bd.png)

**Comment by sagarjagdish** [comment]
I have looked and notice you are verifying this function against live Prosis Pro. Actually we are on stage(testing) version AERA Membership & Prosis Pro both linked with staging(testing) web.

AERA Stage:
http://71.13.159.202/aerastage/

AERA Membership Stage:
http://71.13.159.202/aeramms_stage/Login.aspx

**Comment by omnitekinc** [comment]
@kbt1 If you want to test Prosis Pro & the membership system, you will have to use the Prosis Pro staging site, and it should affect the staging membership site. 

Prosis Pro Stage:
http://71.13.159.202/aerastage/

AERA Membership Stage:
http://71.13.159.202/aeramms_stage/Login.aspx

**Comment by kbt1** [comment]
i have no one to test if the logout function works right now.
so i will close this and if there are issues, will let you know.
