### ISSUE TITLE
Membership Mailing List - need to have discussion on this.

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#169]
Membership Mailing list

Stella: 
I ran a mailing list report in new system and old and Amanda found these differences.
 make sure the contacts with First name only come through and fields aren’t getting cut off.
 One that was missing on the old list, I believe we’ll find are just a case of needing to tell Stella which codes to exclude from the mailing lists as one was a PF and one was an IS.  (don’t want PF – Prospect but want IS – Industry Subscription)

Differences: Stella needs to correct these issues.

14349 lists Automotive Dept as Contact in old.  In new it’s blank
15470 lists Stan as Contact in old.  In new it’s blank
17781 lists Larry as Contact in old. In new it’s blank
29697 lists Steve as Contact in old. In new it’s blank
37273 lists Carlos as Contact in old. In new it’s blank
42514 lists Leandro as Contact in old. In new it’s blank
41372 under Company Inc is getting cut off in the new system.  It’s just I
17417 has an email in new system, but not in old system (we can correct)
44248 has email address in old system, but not the new one (we can correct)

**Comment by sagarjagdish** [comment]
We have resolved this issue on stage and uploaded. Please verify and confirm.

**Comment by kbt1** [comment]
much better.
