### ISSUE TITLE
Regionals - Type

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#17]
When you register someone as an attendee and go in to view the registration they are listed as an exhibitor.

**Comment by omnitekinc** [comment]
Sagar,
Please make sure the type is showing up correctly.
Stella

<img width="1018" alt="screen shot 2017-03-18 at 11 49 35 am" src="https://cloud.githubusercontent.com/assets/7178461/24075017/11e99590-0bd1-11e7-9742-976da9e43d6c.png">

**Comment by sagarjagdish** [comment]
We resolved this issue and now it's working fine. Please add one attendee and exhibitor to verify. I did and it's working for me.

**Comment by amandagoyette** [comment]
Worked for me too.  Thanks!
