### ISSUE TITLE
Email Blast Report - need to discuss

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#170]
I ran an email list in old system and new system.
this was my selection in new system
![image](https://cloud.githubusercontent.com/assets/26387044/26511055/ce2e4ea0-4225-11e7-998a-d42667aa79f6.png)
it only pulled US and CANADA

we may have to change the country part and make 1 selection US and CANADA and another select All.

**Comment by sagarjagdish** [comment]
There is issue with those member who having blank state, we have updated logic like export all member when there is "All" selected. 

Please check this function and let us know if there is any issue.

**Comment by kbt1** [comment]
looks complete now.
