### ISSUE TITLE
Dues and Prosis invoice wording

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#171]
Stella
Just want to let you know we are looking at changing wording on the dues and prosis invoices along with the email portion. Will get this to you asap next week.

**Comment by omnitekinc** [comment]
@kbt1 @aharmening 
Let me know once you have the wording ready, we will update the invoices.

**Comment by kbt1** [comment]
working on it today and we will get it to you once we all agree.

**Comment by stevefox3781** [comment]
Here is what we have come up with. Any questions, let us know. 
[SF - Emailed Invoice Wording.docx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1045537/SF.-.Emailed.Invoice.Wording.docx)
[SF - PRINTED Invoice Wording.docx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1045538/SF.-.PRINTED.Invoice.Wording.docx)

**Comment by sagarjagdish** [comment]
We have changes invoice wording as per provided document file. Please verify and confirm.

**Comment by kbt1** [comment]
Steve - looks good. verify and close.

**Comment by stevefox3781** [comment]
Good
