### ISSUE TITLE
Adding an email coming up wrong

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#172]
I have an email for a member and the new system wont accept it.
rdcm&m@la.twcbc.com    wonder if it doesnt like the & sign in the email? I sent an email and it didnt bounce back.

![image](https://cloud.githubusercontent.com/assets/26387044/26593243/08270a6a-4529-11e7-86e6-439e7699e971.png)

**Comment by sagarjagdish** [comment]
updated validation rules for the email address and now it will consider as valid email in system.

![image](https://cloud.githubusercontent.com/assets/7322922/26633771/1880bbd6-4632-11e7-88d0-7e77a0ba7ebf.png)

**Comment by kbt1** [comment]
good to go.
