### ISSUE TITLE
Email blast issues

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#173]
seems like we found a couple issues with email address fields in the new system
The new system might need larger fields. 

Other differences:
New system missing “m” in .com on Greg Olson’s email: denis@endurancepower.com; greg_olson@nivelparts.co 

New system missing “com” in .com on stephen’s email: info@ventureproducts.com; stephen@ventureproducts.

**Comment by sagarjagdish** [comment]
We have resoled this issue and uploaded on stage. Please verify and confirm.

![image](https://cloud.githubusercontent.com/assets/7322922/26639757/54f6cca2-4643-11e7-91d5-76a42286835b.png)

![image](https://cloud.githubusercontent.com/assets/7322922/26639760/56c991d6-4643-11e7-9063-3ba12788d4b6.png)

**Comment by kbt1** [comment]
good to go.
