### ISSUE TITLE
Membership/Product order form

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#174]
Is it possible to set up the product order form so it is also accessible from a member record?  For membership & PROSIS Renewals I go into the record to confirm information and verify prices then have to back out to the main membership screen to access the form.  It would be nice to save the step if it's doable.

**Comment by sagarjagdish** [comment]
Provided "Product Order From" inside Membership Screen, please let us know if any other change required in this.

![image](https://cloud.githubusercontent.com/assets/7322922/26633674/d2b83778-4631-11e7-9dd1-656005089248.png)

**Comment by amandagoyette** [comment]
Perfect.  Thanks!
