### ISSUE TITLE
Monthly Reports - Quick Prosis Count

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#175]
Stella
The numbers are wrong.
Total count is good.
CMS shows 1200 Web Users.
For Desktop Count, I need actual licenses issued
For Desktop and Web Count, same, need actual license and login issued.

![image](https://cloud.githubusercontent.com/assets/26387044/26632432/cc64f7b4-45d5-11e7-887c-63673a5433b8.png)

**Comment by omnitekinc** [comment]
@kbt1 Karen, we will need to do another update on the database tonight to check and see if the number is accurate.

**Comment by kbt1** [comment]
The Desktop user count needs to be a count of who actually had license keys issued.
Same with Desktop and Web User count, need to be who actually had a license and web account activated.
The numbers are probably off for these 2 counts because you added generic logins for everyone so if we added desktop license then it would be saved. without web logins, they werent being saved at the beginning.

**Comment by sagarjagdish** [comment]
I have restore database and it's updated on stage, however there is difference of 2 user for Prosis Pro count as those user active after restore DB. Once it's liked to production everything will shows correct. I have verified that using direct database query.

![image](https://cloud.githubusercontent.com/assets/7322922/26683247/d0ef9ea2-4700-11e7-87f4-8c1c1e8f6159.png)

**Comment by kbt1** [comment]
please see Issue #181 
Domestic should be more then International count.

**Comment by sagarjagdish** [comment]
Yes, it's only because I restore live database to verify count and now I revert back to stage.

**Comment by omnitekinc** [comment]
@sagarjagdish 
Sagar, the Prosis Pro user count should be based on 1) # of license 2) Active login account
Now you've restored the database, is it accurate?

**Comment by kbt1** [comment]
looks like the numbers are pretty close to CMS.
just need to work on this:
![image](https://cloud.githubusercontent.com/assets/26387044/26699391/52bfd0c2-46df-11e7-992c-95b0188004c1.png)

**Comment by sagarjagdish** [comment]
Let's verify by Monday after production upload. I have compare count with AERA Membership System Stage and Prosis Pro Stage version and both count match with that. So once we link AERA Membership System with live database it will be correct.

**Comment by kbt1** [comment]
I beleive the Desktop and Desktop and Web User counts are wrong.
![image](https://cloud.githubusercontent.com/assets/26387044/26785243/fbd9d2fe-49c6-11e7-8d1a-3e22c5a8ae01.png)

missing monthly count
Per Stella the desktop count and desktop and web user count must be 1) # of license issued 2) Active login account.
example: this company is marked as a desktop user but they havent registered for a license and their web login is inactive.
![image](https://cloud.githubusercontent.com/assets/26387044/26785379/a330a6d6-49c7-11e7-86ea-0f932513e231.png)

The Total count and Pro Web Count are good.

**Comment by sagarjagdish** [comment]
@kbt1  :

Please see below for my comment and let me know if I understood anything wrong. I will implement the same thing for below 2 count calculation.

Prosis Pro Desktop User Count = the total number of the company having a license issued.
Prosis Pro Desktop and Web User Count = the total number of the company having a license issued and active web account.

**Comment by kbt1** [comment]
Yes, that is correct.

**Comment by sagarjagdish** [comment]
We have updated logic as per above can you please check and confirm. Please let me know if any issue.

**Comment by kbt1** [comment]
this looks better.
