### ISSUE TITLE
Tech Assigned - New Call

### ISSUE THREAD

**Issue by stevefox3781** [omnitekinc/AERA_MSS_Clients#176]
Currently when you open a new tech call, you have to pick your name to assign you to the call. We would like it when you open a call, it is automatically assigned to you. Once in the call if that call is for another tech, then the original tech can change who the call is assigned to. 

![tech assign](https://cloud.githubusercontent.com/assets/26387391/26642633/158651a4-45f4-11e7-90e1-bc9fa82f444c.jpg)

**Comment by sagarjagdish** [comment]
We have implemented function as suggested for new tech call. Please verify and confirm.

**Comment by stevefox3781** [comment]
Works
