### ISSUE TITLE
Tech Calls Unassigned - Multiple Tech in Call & Taking Over In Process Calls

### ISSUE THREAD

**Issue by stevefox3781** [omnitekinc/AERA_MSS_Clients#177]
Had an issue the other day where I went to work on a call not assigned and someone else grabbed the same call so we both were working on it at the same time making changes. Once a tech call is taken from the queue, who ever took the call should automatically assigned to the call, just like opening a new call. 

Also, if a tech has a call "In Process" and someone clicks on that call to take it over, we would like a prompt box to display saying something like "This is currently being worked on by (tech name) would you like to take this call over?" YES or NO. If Yes is selected, the new tech takes the call over and then an email is sent to the original tech letting them know that someone else has taken control of that call. This can happen is a tech has a call in process and leaves for vacation, gone to lunch or 1/2 day work and member calls back. 

Hope this all makes sense and if any questions, let me know.

**Comment by sagarjagdish** [comment]
We have implemented suggested function for the tech call. 

Can you please take a look and confirm it's working as per your expectation or not?

**Comment by stevefox3781** [comment]
When I click on the call and the box opens up, I click NO and it takes me into the call. It should just return the tech queue. Other than that, seems to work fine.

**Comment by sagarjagdish** [comment]
Okay. got that. let us do that.

**Comment by stevefox3781** [comment]
Also it seems that if a tech has a call in process and wants to go back into that call, the box pops up asking if they want to take the call over. If Steve has a call In Process and Steve goes back into that call from the tech queue, it should just open up and not ask if they want to take it over.

**Comment by sagarjagdish** [comment]
++++++++++++++++++
When I click on the call and the box opens up, I click NO and it takes me into the call. It should just return the tech queue. 
++++++++++++++++++
=> We have taken action as suggested above.

++++++++++++++++++
Also it seems that if a tech has a call in process and wants to go back into that call, the box pops up asking if they want to take the call over. If Steve has a call In Process and Steve goes back into that call from the tech queue, it should just open up and not ask if they want to take it over.
++++++++++++++++++
=> You are correct. It should work as per you above comment. I have take a look and make it proper. Please review this function on stage and let me know if any other change required in this.

**Comment by stevefox3781** [comment]
All good.
