### ISSUE TITLE
Engine Search Not Found From Tech Queue

### ISSUE THREAD

**Issue by stevefox3781** [omnitekinc/AERA_MSS_Clients#178]
Member called in looking for specs and when I searched in Membership Software, the search comes up with "Your search did not return any results". Found the engine searching the same way in PRO web and in CMS as the engine was listed in both. 

![tech call engine search](https://cloud.githubusercontent.com/assets/26387391/26643005/71352768-45f5-11e7-87e6-603aaaf9475b.jpg)

**Comment by sagarjagdish** [comment]
We have make that things proper now. Please refer below image.

![image](https://cloud.githubusercontent.com/assets/7322922/26685116/c2cfb7ac-4706-11e7-9067-729865f08f26.png)

**Comment by stevefox3781** [comment]
Looks good.
