### ISSUE TITLE
Membership - Product Order Form

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#179]
When using the product order form in the member record I enter the expiration date in the standard format: 
![image](https://cloud.githubusercontent.com/assets/26386841/26651647/fa5ba540-4612-11e7-9504-0adb160345e9.png)
but when Karen gets the email it's blank:
![image](https://cloud.githubusercontent.com/assets/26386841/26651672/1356c9e4-4613-11e7-893b-af4984944fd1.png)

We never had an issue when using the button on the main page.  However, can we update the expiration date in both spots so this calendar doesn't come up:
![image](https://cloud.githubusercontent.com/assets/26386841/26651717/41e39f80-4613-11e7-8f8d-5450beebd9ae.png)

Since it's a credit card date we don't need a specific calendar day.  We simply need a spot to type the format mm/yy 

Thanks!

**Comment by sagarjagdish** [comment]
all above reported issue address on stage. Please verify and confirm.

**Comment by amandagoyette** [comment]
Looks good.  I'm just going to leave it open until I get an opportunity to test it.

**Comment by kbt1** [comment]
I was testing using the Product Order Form under the customer ID#, I can only enter 1 Item, the "add" button doesnt work.
![image](https://cloud.githubusercontent.com/assets/26387044/26728799/0d9624a0-4771-11e7-82ad-30085a44aa9f.png)
I added Tubing and then wanted to add an additional item and nothing happens.

The Product Order Form on the main page of Membership works fine. Just not the button in the actual membership record.

**Comment by sagarjagdish** [comment]
We have addressed this issue and resolved on stage. Please verify and confirm.

**Comment by kbt1** [comment]
The product order form works good now and allows multiple items to be added.

Amanda - close when you are ready.

**Comment by amandagoyette** [comment]
looks good
