### ISSUE TITLE
Regionals - Price

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#18]
When you add a exhibitor it wants to bill the attendee price.  When you view details it shows the additional attendee price as the exhibitor price for both exhibitors and attendees.

**Comment by omnitekinc** [comment]
Sagar, this is related ot #17

**Comment by sagarjagdish** [comment]
resolved https://github.com/omnitekinc/AERA_MSS_Clients/issues/17 and I also verified this one and it's resolve as well.

**Comment by amandagoyette** [comment]
looks good
