### ISSUE TITLE
Dues Processing Tab, Export Data

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#180]
I was just going to run a monthly payment report 
this is what i filled out
![image](https://cloud.githubusercontent.com/assets/26387044/26651745/58ff498a-4613-11e7-8e70-8ed5b03c4fc3.png)

this is what i get when i click export.
![image](https://cloud.githubusercontent.com/assets/26387044/26651770/66072846-4613-11e7-8d10-5a8b78cce933.png)

**Comment by sagarjagdish** [comment]
This issue is resolved now. Please try and confirm.

**Comment by kbt1** [comment]
looks like they work.
