### ISSUE TITLE
Prosis Accounts

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#181]
Looks like US accounts are all coming up Outside US accounts after you updated system last night.
i have run across 4 of these so far this morning

![image](https://cloud.githubusercontent.com/assets/26387044/26681115/94ec3faa-46a1-11e7-8d6d-72c97f05f49f.png)

expiration dates might have been messed up also. I just got a call from a member that paid and now their expiration date is set back to 6/1/17 again. I manually adjusted the date.

**Comment by sagarjagdish** [comment]
I just restore company database to make sure about count and revert that change after verification. Please verify now and confirm.

We have plan to link AERA Membership with live database on this weekend so from coming Monday it will shows up everything from the live.

We will follow below step to go live.

1) flush new AERA Membership database, all changes on stage will be flushed.
2) Restore MS Access database to new AERA Membership system.
3) Reload all automated generated dues batch to AERA Membership back which we did in past few days.
3) Link new AERA Membership with live Prosis Pro.

Please let us know if you have any feedback on this. Once this process done you have to maintain data to the new AERA Membership system as well.

**Comment by kbt1** [comment]
data fixed.
we have been maintaining old and new databases.
