### ISSUE TITLE
Going Live Monday June 5th 

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#182]
Should we expect to see new links for the "Live" version of the Membership system Monday morning?

**Comment by omnitekinc** [comment]
@kbt1 Karen, we will provide a new link to the system on Monday. But we don't have an URL for the system, so it will be in IP address. Unless AERA want to have a proper URL, example aera-membership.com

**Comment by amandagoyette** [comment]
Perfect.  Thanks Stella!

**Comment by stevefox3781** [comment]
IP Address works
