### ISSUE TITLE
Current Membership

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#184]
I was looking over current membership and as of June 1, there are still April and May expired members.
just want to make sure these will go to Expired Tab.
So July 1, all June 1 should go to expired tab.

**Comment by omnitekinc** [comment]
Karen, I think the current logic is: The member will move to expired after their membership has expired for over 60 days.

**Comment by kbt1** [comment]
I thought it was the following month. So if you expire May 1, it will go to expired June 1 and so on.
We can keep it at 60 days. I was just looking things over.
