### ISSUE TITLE
Membership Invoice - Email Text and Printed Invoice Text

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#185]
ID#39749 i printed membership renewal but the total due is wrong.
Also, please correct the text in the last sentence below: **this needs to be corrected on email and printed invoice text.**

Dear AERA Member:
Your company’s AERA Membership is about to expire.  AERA offers many services & benefits to it members, the main one being the Technical Services Department which supplies technical information to the machine shop. To avoid any interruption in yourservices,the AERA Membership will need to be renewed.
**(Correction: To avoid any interruption in your services, the AERA Membership will need to be renewed.)**

Membership Expiration Date: 06/01/2017
Amount Due: $399.00

**Total Amount Due: $858.00  (wrong amount due)**

**Comment by sagarjagdish** [comment]
updated text as suggested please verify and confirm.

**Comment by kbt1** [comment]
text is good.
