### ISSUE TITLE
Printing Membership and Prosis Invoice

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#186]
I test printed this members #44147 invoice for Membership and Prosis, only Prosis came up on the invoice.
Membership expired 6/1/17 and Prosis expires 7/1/17. They should both print on the invoice.

![image](https://cloud.githubusercontent.com/assets/26387044/26785498/54947506-49c8-11e7-8be6-7d5996f70455.png)

Looks like there are issues with invoicing. I checked #698 and both membership and prosis should print on the invoice, only membership did. please check how invoicing is pulled.
![image](https://cloud.githubusercontent.com/assets/26387044/26785602/de17c008-49c8-11e7-8a81-982215df5cde.png)

**Comment by sagarjagdish** [comment]
We have addressed this issue, can you please verify and confirm now?

![image](https://cloud.githubusercontent.com/assets/7322922/26829086/b213208c-4ae1-11e7-9a1a-6826396c686d.png)

**Comment by kbt1** [comment]
ID#12425 Membership is due but the total due is $858.00 in the email text
![image](https://cloud.githubusercontent.com/assets/26387044/26832247/7a755070-4a94-11e7-886f-bf5a5246f450.png)
When i select print, it prints 2 invoices, 1 is for membership due and the other is for Prosis which is not due until 2018. Nothing paid or with current expiration dates should print.
[ID#12425.pdf](https://github.com/omnitekinc/AERA_MSS_Clients/files/1055199/ID.12425.pdf)

**Comment by sagarjagdish** [comment]
@kbt1  : Okay so in this case what should we have to show in email and print invoice when Member or Prosis Pro expiration date having long duration to expire like more than 90 or 100 days.

can you please suggest to we can update system with proper check?

**Comment by kbt1** [comment]
If Membership or Prosis Pro expiration date is current 90 days past the other expiration date, then just print the invoice that is due.
So if Membership expires July 1 2017 and Prosis Expires 12/1/17, only Membership invoice will print/email
Same with the other way around.

If Membership expired 90 days and Prosis is due, then both fees should be on invoice.
So if Membership expired 5/1/17 and Prosis expires 8/1/17, both will print/email

let me know if you have any questions.

**Comment by sagarjagdish** [comment]
Okay I am clear with that point which you listed about now my question is for below case please see and give me your comment on this.

1) If Membership expires Sept 1 2017 and Prosis Expires Sept 1 2017, today we click on generate invoice then what should happen for Print/Email invoice.

2) If Membership expires Sept 1 2017 and Prosis Expires Oct 1 2017, today we click on generate invoice then what should happen for Print/Email invoice.

**Comment by kbt1** [comment]
Correct.
also, if membership or prosis expire Sept 1 2017 and one of the other expired previously in June 2017, i want both to print or email.

**Comment by sagarjagdish** [comment]
I did testing for below member and it's generating invoice as below please verify from your end and let me know if any change required in this.

#44147  >> Membership expired 6/1/17 and Prosis expires 7/1/17 >> combine print/email invoice.
#12425 >>  Membership expired 6/1/17 and Prosis expires 6/1/18 >> print/email only membership invoice.
#11342 >>  Membership expired 5/1/18 and Prosis expires 5/1/16 >> print/email only Prosis Pro invoice.
#3602 >>   Membership expired 7/1/18 and Prosis expires 8/1/18 >> nothing to print/email invoice.
#2795 >>   Membership expired 8/1/17 and Prosis expires 10/1/17 >> print/email only membership invoice as Prosis Pro expiration having more than 90 days.

**Comment by kbt1** [comment]
works good.
