### ISSUE TITLE
Duplicate Tech Call

### ISSUE THREAD

**Issue by stevefox3781** [omnitekinc/AERA_MSS_Clients#188]
When a member calls in with two questions and you go to duplicate the call, the information from the original call is converted to the duplicate call. The only information that should transfer to the duplicate call is the member information and the tech name. Engine information, problem, answer etc should all be cleared out. Any questions let me know.

**Comment by sagarjagdish** [comment]
This function already exist in new website. Please see below image. This user is Active and shown as Green color. If you want to Inactive then just click on that and it will be Inactive and will show as Red color.

![image](https://user-images.githubusercontent.com/7322922/26886187-66dcb92a-4bc2-11e7-9dc6-9069dfd3d18d.png)

**Comment by sagarjagdish** [comment]
now only member information and the tech name copied in duplicate call. Please check and confirm.

**Comment by stevefox3781** [comment]
Works good. Thank you!!!!!!!
