### ISSUE TITLE
2 Membership records -= PLEASE DELETE

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#189]
are you going to delete these? i just found them.
![image](https://user-images.githubusercontent.com/26387044/26845265-8a5a5748-4abb-11e7-8127-f3d9b397796d.png)

**Comment by kbt1** [comment]
Sagar
Please delete these 2 records, i need to add a new member and want them to go in sequential order.

**Comment by sagarjagdish** [comment]
@kbt1 : It's done, sorry for the delay. Please check.

**Comment by kbt1** [comment]
thank you!

**Comment by kbt1** [comment]
Sagar:

Can you delete the Prosis connected to these records also.

**Comment by sagarjagdish** [comment]
@kbt1 deleted those testing member from the Prosis as well.

**Comment by kbt1** [comment]
All the prosis info is still attached to #44280 - changed to a 30 day trial and info does not change.
![image](https://user-images.githubusercontent.com/26387044/26884819-582da918-4b66-11e7-989a-86cae003cf81.png)

**Comment by sagarjagdish** [comment]
Okay..let me check. I have removed that account but may be there is more other places the need to check.

**Comment by sagarjagdish** [comment]
@kbt1  For the #44280 you don't want Prosis Pro information, correct?

**Comment by kbt1** [comment]
for #44280 and #44281 both need Prosis completely cleared from records.

**Comment by kbt1** [comment]
let me know when done.

**Comment by sagarjagdish** [comment]
Please see below image, 44281 not exist in system and 44280 have no Prosis Detail.

![image](https://user-images.githubusercontent.com/7322922/26887087-b997d38c-4bc4-11e7-8346-7ecc0df0ebed.png)


![image](https://user-images.githubusercontent.com/7322922/26887124-cc2837f8-4bc4-11e7-9a97-cc94e5ebc037.png)

**Comment by sagarjagdish** [comment]
Please let me know if still you are facing any issue.

**Comment by kbt1** [comment]
perfect.

**Comment by kbt1** [comment]
I went to add a 30 day trial login and it was successfully added, however, i get this error when i pull their membership record up in new system #44280

![image](https://user-images.githubusercontent.com/26387044/26887887-f688a164-4b6e-11e7-91a6-36917e670a25.png)

when i go into CMS to check their account, i get this error:

![image](https://user-images.githubusercontent.com/26387044/26887979-4d65c674-4b6f-11e7-8d8f-67bc1a46cd17.png)

**Comment by kbt1** [comment]
I cant even open record #44280 now.
![image](https://user-images.githubusercontent.com/26387044/26889656-7744bc3e-4b74-11e7-8e14-6d06f775075a.png)

**Comment by sagarjagdish** [comment]
@kbt1 It's occur because there is blank Expiry data for Prosis Pro account, earlier we have no blank expiry date for Prosis Pro. I have manage that case for now. Please check.

I have manage that case in New Membership System only. Please add Expiry date for the Prosis Pro 30 Days Trial and it will work in CMS as well.

**Comment by kbt1** [comment]
PERFECT.
