### ISSUE TITLE
Conference Registration/Setup

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#19]
Add: Non Member Exhibitor Box and ability to set price
we do get some non members that sign up to exhibit and they pay more then members.

![image](https://cloud.githubusercontent.com/assets/26387044/24060246/683f6e80-0b20-11e7-9cfd-2ef54d9d3184.png)

**Comment by omnitekinc** [comment]
Please add "Non Member Exhibitor" next to "Exhibitor" And make sure this pricing option is avaliable when people are registering.
<img width="420" alt="screen shot 2017-03-18 at 11 53 41 am" src="https://cloud.githubusercontent.com/assets/7178461/24075045/a804e2f0-0bd1-11e7-88f7-8bbb2b7d5363.png">

**Comment by kbt1** [comment]
There needs to be a Non-Member Exhibitor Box also next to Exhibitor box.
There are 2 different prices for members and non-members that exhibit.

**Comment by sagarjagdish** [comment]
added function to add non-members exhibitor price in conference screen. also added option to select non-members exhibitor during registration and show price based on that selection. 

Please verify and confirm.

**Comment by kbt1** [comment]
good
