### ISSUE TITLE
Prosis Pro Tab

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#190]
I need the Active/Inactive box in the new membership system 
this is what it is in CMS
![image](https://user-images.githubusercontent.com/26387044/26845672-ddb8f83a-4abc-11e7-9bc4-f83371983cd4.png)

**Comment by sagarjagdish** [comment]
This function already exist in new website. Please see below image. This user is Active and shown as Green color. If you want to Inactive then just click on that and it will be Inactive and will show as Red color.

![image](https://user-images.githubusercontent.com/7322922/26886187-66dcb92a-4bc2-11e7-9dc6-9069dfd3d18d.png)

**Comment by kbt1** [comment]
Please change so it says Active when green and Inactive when red not expired.
this is for Inactive web logins that want to activate the login now. Not so show current or expired.
like this one in CMS:
![image](https://user-images.githubusercontent.com/26387044/26887449-a9d4beb2-4b6d-11e7-8578-702eec170bcd.png)

**Comment by kbt1** [comment]
Please change so it says Active when green and Inactive when red not expired.
otherwise, works good.

**Comment by sagarjagdish** [comment]
changed label from expired to inactive. please verify and confirm.

**Comment by kbt1** [comment]
good.
