### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#192]
Trying to run month end report for New Membership Report and getting error
![image](https://user-images.githubusercontent.com/26387044/26890135-26cf8ffc-4b76-11e7-89e0-261119d70753.png)
please let us know if there are issues.
CMS doesnt seem to be working
I cant get into ID#44280 in new system

**Comment by sagarjagdish** [comment]
I cant get into ID#44280 in new system
=> It's working now. There is issue with Prosis Pro expiry date for that Member.

**Comment by kbt1** [comment]
all ok
