### ISSUE TITLE
Searching for a member by company name

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#193]
I am searching for g & s auto parts
![image](https://user-images.githubusercontent.com/26387044/26896921-31bfa346-4b8c-11e7-9bc8-6bf55ee585ec.png)

after i click search, this is what i get 
![image](https://user-images.githubusercontent.com/26387044/26896937-44a2554e-4b8c-11e7-8fc1-e4eae838a863.png)

so instead i search for their member #502 and they are there
![image](https://user-images.githubusercontent.com/26387044/26896970-5e79c862-4b8c-11e7-8918-0c553645933e.png)

not sure why company name search doesnt work. i tried both g & s auto parts and G & S Auto Parts and when i click search, nothing happens.

**Comment by sagarjagdish** [comment]
Please see below image. now search option with "&" is working on live.

![image](https://user-images.githubusercontent.com/7322922/26920031-4a72174c-4c55-11e7-9e26-54350e4771d3.png)

**Comment by kbt1** [comment]
works good now
