### ISSUE TITLE
Monthly Report Tab - New Membership Report  Error Message

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#194]
I put in an expiration date of 7/1/2016 using the calendar in the New Membership Report box
![image](https://user-images.githubusercontent.com/26387044/26897397-0b8f03fe-4b8e-11e7-85a2-7a39faa2063f.png)

and get this error
![image](https://user-images.githubusercontent.com/26387044/26897430-2c05b786-4b8e-11e7-8e2b-77b51f885449.png)

**Comment by sagarjagdish** [comment]
we have resolved this error, please check and confirm.

**Comment by kbt1** [comment]
works good now
