### ISSUE TITLE
Printing and Emailing Invoices

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#195]
ID#33871 PAI Industries. both Membership and Prosis Expire 6/1/17.
 I select their record and click on print invoice, i only get a prosis invoice.
I select email invoice and it includes both Membership and Prosis fee.

please look into this.

Thank you.

**Comment by sagarjagdish** [comment]
Please see below image. I tired same and it's printed both together for me, please confirm we all are using live URL for all new issue.

Live :
http://71.13.159.202/aeramms/membership.aspx

![image](https://user-images.githubusercontent.com/7322922/26913500-d38f0098-4c38-11e7-94c1-16bff1c6e054.png)

![image](https://user-images.githubusercontent.com/7322922/26913509-dff8823c-4c38-11e7-969b-460e4b45d051.png)

Both having expiry within 90 days so both printed together.

**Comment by kbt1** [comment]
works fine now.
