### ISSUE TITLE
Monthly Report: Active Member Locator - Website

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#196]
can you add Phone Fax and Email to this report.

**Comment by sagarjagdish** [comment]
I have checked and it's already there. I have attached exported file there. Please let me know if any other information need to include in this report.

[ActiveMemberReport-Website-5900 (2).xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1063417/ActiveMemberReport-Website-5900.2.xlsx)

**Comment by kbt1** [comment]
looks good
