### ISSUE TITLE
Membership/Prosis Invoices

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#197]
ID#17268
Membership expires 6-1-17
Prosis expired 6-1-15

both show up on invoice for emailing, it should only be Membership. Prosis is expired 2 years.
same with printing, it should only print Membership since Prosis is expired 2 years.

**Comment by sagarjagdish** [comment]
We have addressed issue for ID#17268. now it's exporting only membership invoice as Prosis expired before 2 year. We have exclude those Member/Prosis user from invoice who expired before 1.5 year.

Pleases review updated and let me know if any change required in this.

**Comment by kbt1** [comment]
good to go
