### ISSUE TITLE
Prospects Tab

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#198]
It would be nice to be able to add an attachment to an email under the Prospects Tab

![image](https://user-images.githubusercontent.com/26387044/26993684-e8bb7108-4d29-11e7-88b9-a13509821359.png)

let me know if this is possible.

**Comment by sagarjagdish** [comment]
Please see below image. We have added function to attached file with prospect email function. Please review and let us know if any change.

![image](https://user-images.githubusercontent.com/7322922/27081182-d54dac0e-505c-11e7-85d6-59281fa6e315.png)

**Comment by kbt1** [comment]
perfect
