### ISSUE TITLE
Non Existing member id number

### ISSUE THREAD

**Issue by Dphagen** [omnitekinc/AERA_MSS_Clients#199]
A caller called and gave non existing ID number such as 4240,  While in the Tech Queue and clicking on Create New Tech Call, I put in the 4240 and it creates a call with no information in it. I don't think we want that.

**Comment by sagarjagdish** [comment]
@omnitekinc  :  can you please suggest which action need to take for such non existed number? should system stop to create teach call for such number or what?

**Comment by Dphagen** [comment]
How about the phrase “Invalid ID Number” pops up and the entry box is still there for another try.

Dave

**Comment by sagarjagdish** [comment]
We have address this issue as suggested. Please refer below image.

![image](https://user-images.githubusercontent.com/7322922/27132055-f65eaed8-512a-11e7-85c2-d4a37f8ca8af.png)

**Comment by kbt1** [comment]
Dave, this works good.
Please log into the Github.com and close this issue.

**Comment by kbt1** [comment]
tested, works good. closing.
