### ISSUE TITLE
Closed Calls - List Order

### ISSUE THREAD

**Issue by stevefox3781** [omnitekinc/AERA_MSS_Clients#2]
When in the Tech Que and we want to look at Closed Calls, the most recent Closed Calls should be listed first. Currently they are listed last and you need to go to the last page to view them. 

![closed call listing](https://cloud.githubusercontent.com/assets/26387391/23915969/a7efb658-08b8-11e7-831e-f7559b51b5aa.jpg)

**Comment by sagarjagdish** [comment]
We changed order and now close call showing most recent first. Please let me know if any change required in open call order. currently we are showing most recent last in open call tab.

**Comment by stevefox3781** [comment]
Open calls are good the way they are, oldest on top, most recent last. 

Thank you,

**Comment by omnitekinc** [comment]
Hi Steve, please close the ticket if you approve the changes.
