### ISSUE TITLE
Dues Processing - Error Message

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#20]
When I tried not to use the usual alpha-numeric title for my batch and called it Old Member Rejoining it wouldn't let me add the member I wanted.  I redid it and called my batch 31717ah and had no problems.  If we need certain criteria for the batch there should be an error if you're not titling it right.  

Also, I received this error message when trying to add the member to my batch Old Member Rejoining, but the error message doesn't really tell me why it doesn't work...
![error mbr 12923](https://cloud.githubusercontent.com/assets/26386841/24060566/d4ee41ae-0b21-11e7-8e48-9d894954174f.JPG)
It leads me to think maybe that member doesn't exist, but they did/do:
![member record 12923](https://cloud.githubusercontent.com/assets/26386841/24060575/e9e2332c-0b21-11e7-9bb9-1a2025904ee0.JPG)

**Comment by omnitekinc** [comment]
Hi Amanda,
Sorry, we are still finishing up Due and Processing, Please hold off on doing any testing on that section also the invoicing, we are still working on.
Stella

**Comment by amandagoyette** [comment]
Sounds good Stella!  I had some members to play with so I was trying it out.  You'll see another bug I submitted as I received this note.  I mentioned on there to just ignore if it's the same scenario.  Thanks!

**Comment by omnitekinc** [comment]
Thanks! I love how everyone are working so hard testing the system, it's great! I will read your notes and sort the ticket accordingly.

**Comment by sagarjagdish** [comment]
We done with dues, please continue to work with dues screen.

**Comment by amandagoyette** [comment]
@kbt1 It sounds like the dues processing is ready for some in depth testing in case you didn't know.
