### ISSUE TITLE
Closed Call Search

### ISSUE THREAD

**Issue by stevefox3781** [omnitekinc/AERA_MSS_Clients#200]
When I do a close call search under engines, the results come up fine. When I go into one the closed calls from the search results and back out to look at others, it removes the LITER field that was inputted. When we return the the closed call search results, the engine information originally searched should still be there. Any information that has been entered for the engine search should remain in the Closed Call Search Fields.
 
![closed call search results](https://user-images.githubusercontent.com/26387391/27044525-723bd93c-4f63-11e7-9ea9-68b7131bd253.jpg)

![closed call results after looking at a closed call](https://user-images.githubusercontent.com/26387391/27044528-788f50ac-4f63-11e7-9a08-bab1d7d643cc.jpg)

**Comment by sagarjagdish** [comment]
We have resolved this issue. Please verify and confirm.

**Comment by stevefox3781** [comment]
Works good!!! Thank you,
