### ISSUE TITLE
Fax number removed from tech call when editing 

### ISSUE THREAD

**Issue by stevefox3781** [omnitekinc/AERA_MSS_Clients#201]
We found out that when you go into a call to edit it, the fax number is removed. Please see screenshot below. 

![fax number](https://user-images.githubusercontent.com/26387391/27106352-af40c27a-5058-11e7-9bfe-8f2974451587.jpg)
![fax number missing](https://user-images.githubusercontent.com/26387391/27106370-c7f5542a-5058-11e7-9599-25dd945ad1be.jpg)

**Comment by sagarjagdish** [comment]
We have resolved this issue. Please refer below image. 

![image](https://user-images.githubusercontent.com/7322922/27132089-1ebd06d6-512b-11e7-92fd-4f74d75c7ce2.png)

**Comment by stevefox3781** [comment]
Good -- Thank you!
