### ISSUE TITLE
Membership - Zip Code Alpha Numeric

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#203]
I can not enter an alpha numeric zip code in the mailing address but i can in the shipping address.
can you please fix so they both accept alpha numeric postal codes. (ID#44284)

![image](https://user-images.githubusercontent.com/26387044/27338833-cfc68afa-559b-11e7-93fe-31724a08c9f9.png)

**Comment by sagarjagdish** [comment]
We have done with this request. Please verify and confirm.

**Comment by kbt1** [comment]
good to go
