### ISSUE TITLE
Membership - Monthly Reports - New Membership Report

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#204]
Tab 2 is a summary sheet.  The final column is a running total of something, and I'm unsure what.  It would be nice if it would give us the running total of new members for the fiscal year we are pulling. The number there now doesn't do us any good.
This is the original Report:
[NewMembershipReport-8500.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1092154/NewMembershipReport-8500.xlsx)
This is what I'd propose:
[NewMembershipReport- FIXED Total Column.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1092163/NewMembershipReport-.FIXED.Total.Column.xlsx)

**Comment by sagarjagdish** [comment]
We have done with change and uploaded changes on production. please verify change and let us know if any query.

**Comment by kbt1** [comment]
I went through all the new members from 7/1/2016 to current and entered all the membership sources.
they are now gone?????
[New membership worksheet sample.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1094878/New.membership.worksheet.sample.xlsx)

**Comment by amandagoyette** [comment]
@kbt1 Also, you have two more new members on your sample then the exported worksheet. Mbr 34839 & mbr 43147 (may reinstated) are not on the new spreadsheet, but are on the sample you attached this morning.

**Comment by kbt1** [comment]
Stella
Any idea how all my Membership Sources have disappeared?

I went through all the new members from 7/1/2016 to current and entered all the membership sources.
they are now gone?????
New membership worksheet sample.xlsx

**Comment by omnitekinc** [comment]
Probably got dropped when we are updating something.
@sagarjagdish can you please add it back? And find out the cause of the problem

**Comment by sagarjagdish** [comment]
I have looked into this issue and notice all those source setup on stage not on production. I have updated source from stage to production and now it's start showing in report.

Please verify update on production and let us know if any query.

**Comment by kbt1** [comment]
thank you for correcting.
