### ISSUE TITLE
Adding 2 columns to Membership

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#205]
Hi Stella
Something I just ran across was looking up a company called Arnold Motor Supply.
There are 20 locations and they didnt know their ID# or info under that company location (it was an IT guy calling about Prosis), so it would help to have 2 columns added after the Company Name Column, add City and State Columns.
That way when a company has multiple locations, it would be easier to find listed.

**Comment by omnitekinc** [comment]
@kbt1 How many members have multiple addresses? And how did you handle this in the old system?

**Comment by kbt1** [comment]
this is what the old system looked like
![image](https://user-images.githubusercontent.com/26387044/27404319-2f32ea4a-5693-11e7-9745-e9223e35e8dc.png)
this is the new system
![image](https://user-images.githubusercontent.com/26387044/27404331-3b1c73e4-5693-11e7-800c-9b4fe2a3ed30.png)
Napa, Carquest, Arnold Motor Supply and I am sure there are others that have same names and several member locations.

**Comment by omnitekinc** [comment]
@sagarjagdish can you look into this and see if we could add the info?

**Comment by kbt1** [comment]
You could even make it 1 column and make it City, State.
that would make it a lot easier.

**Comment by sagarjagdish** [comment]
We have added column with named "Location" which include "City, State". Please verify and confirm our change.

**Comment by kbt1** [comment]
perfect!
