### ISSUE TITLE
Membership and Prosis Invoices

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#207]
I just ran invoices that I am going to print July 1 and noticed 1 problem.
The amount due should be the renewal fee excluding any contributions or discounts from the previous year.  If you look at Member #125, Membership due should be $399, not $449 with contributions. We cant assume anyone is contributing money if they did the previous year. 
Attached are 5 samples i found. 
All invoices should be for the current membership or prosis fee due.
please correct and let me know when done.
Thank you!
[Invoices Printing wrong amounts due.pdf](https://github.com/omnitekinc/AERA_MSS_Clients/files/1103405/Invoices.Printing.wrong.amounts.due.pdf)

**Comment by sagarjagdish** [comment]
We have resolved this issue on stage & Production. Please verify.

**Comment by kbt1** [comment]
good to go
