### ISSUE TITLE
URGENT REPLY REQUESTED - monthly batch

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#208]
i have created my spreadsheet for the monthly credit cards and I am getting this error.
it needs to fixed ASAP, everyone is locked out of Prosis software. I need to get this posted.

![image](https://user-images.githubusercontent.com/26387044/27693555-6181c4cc-5caf-11e7-85c6-185d7ef21a45.png)
I have saved it on my desktop, on my "M" drive, renamed it and it wont work.

If this cant be fixed right now so i can get these posted, can you change all monthly dates from 6/1/17 to 7/1/17 ASAP.

**Comment by sagarjagdish** [comment]
let me look into this error.

**Comment by kbt1** [comment]
here is the spreadsheet.
[Monthly Credit Card 062917.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1112421/Monthly.Credit.Card.062917.xlsx)

**Comment by sagarjagdish** [comment]
+++++++
If this cant be fixed right now so i can get these posted, can you change all monthly dates from 6/1/17 to 7/1/17 ASAP. 
+++++++
Updated exp. date as before.

**Comment by sagarjagdish** [comment]
@kbt1 : can you please try with same file now?

**Comment by kbt1** [comment]
working on it now.
thank you.

**Comment by kbt1** [comment]
Processed checking and uploaded and got this error
![image](https://user-images.githubusercontent.com/26387044/27699267-54a459e4-5cbf-11e7-88c6-ed08a576a90c.png)

Payment method is check
Payment term is marked as 2 or more because they are paying June and July to equal 8/1/17 exp date
and 1 member paid 10 months to pay off the monthly.
can you allow multiple terms?

let me know as soon as you can.

**Comment by kbt1** [comment]
Error invalid payment term.
i changed them all back to 1 
not sure why this wont work but the credit cards worked fine.   **error message and spreadsheet attached.**

![image](https://user-images.githubusercontent.com/26387044/27706286-ae1cf852-5cd6-11e7-8a9f-1cd138b5e20c.png)
[Monthly Checking 062917.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1113296/Monthly.Checking.062917.xlsx)

**Comment by kbt1** [comment]
I will work with that this morning.
Can you do this, We had talked to Stella about it but I dont think it got implemented and now any monthly who hasnt been posted is locked out and we dont want that.
**Can we also add a function for Prosis Pro - Only Monthly Accounts: Adding a 30 days buffer for Prosis Pro logout date. Currently, if the monthly Prosis Pro user expired on June 1st, they will not be able to login to Prosis Pro. This should not change the expiration date, it just giving the user additional time to pay for their monthly without getting logout.**

**Comment by sagarjagdish** [comment]
+++++++++++++++
Can you do this, We had talked to Stella about it but I dont think it got implemented and now any monthly who hasnt been posted is locked out and we dont want that.
+++++++++++++++
Yes, we can do that. I will implement this function and update you.

**Comment by kbt1** [comment]
please implement as soon as possible.

**Comment by kbt1** [comment]
check worked good today. 
once you implement the 30 day buffer and i test, i will close these and looks like things will be good to go.
Thank you!

**Comment by sagarjagdish** [comment]
We done with quick implementation like allowing Prosis Pro user with 30 days buffer time. So all Prosis Pro user can do login right now. It's already uploaded on production so no need to worry about that.

We will provide you option to change that 30 days buffer time from your end using membership screen like below. 

![image](https://user-images.githubusercontent.com/7322922/27738811-2230f934-5dca-11e7-8244-298db100a02d.png)

**Comment by kbt1** [comment]
that is perfect, however i checked and i do not see that Buffer Box.

**Comment by sagarjagdish** [comment]
@kbt1 : We have uploaded box on production. Please refer below image. It's after Expiration Date.

![image](https://user-images.githubusercontent.com/7322922/27739856-ab51fa1c-5dcd-11e7-8759-6c1ba17ce751.png)

**Comment by kbt1** [comment]
that is perfect.
let me share with others and test.

**Comment by kbt1** [comment]
monthly bulk batches worked perfectly.
30 Day Buffer works good.
