### ISSUE TITLE
Monthly Payments printing on Invoices

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#210]
Monthly Payments are not supposed to print or email on any invoices.
I was going to email a membership invoice and their Prosis Monthly payment is pulling on it also.

![image](https://user-images.githubusercontent.com/26387044/27751325-60399e3a-5da1-11e7-8790-75d0e2394d43.png)

please fix.
I want to be able to print or email invoices without the monthly payment on it.
There are companies that are on the monthly payment plan for 1 and pay in full for the other.

**Comment by sagarjagdish** [comment]
We have addressed this issue. can you please take a look?

**Comment by kbt1** [comment]
good to go!
