### ISSUE TITLE
Email Invoice

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#211]
I selected ID#42720 membership expiration date 7/1/17 to email invoice.
their record is checked and they have an email address and I get this message:
![image](https://user-images.githubusercontent.com/26387044/27800160-c909201e-5fdd-11e7-91db-1eef8fcdf30f.png)
this also happened with ID#125
![image](https://user-images.githubusercontent.com/26387044/27800513-4f3c7a22-5fdf-11e7-831c-44278eb5bf46.png)

let me know when fixed.  Also, please correct spelling in message box to **proper** not peoper.

Seems that the records that I get the error message for have current prosis exp dates.

**Comment by sagarjagdish** [comment]
It's resolved on production. Please take a look and let us know if any query.

**Comment by kbt1** [comment]
they work now  but coming up with **Total Amount Due: $##TOTALAMOUNTDUE##**

**Comment by sagarjagdish** [comment]
We have taken action on that as well. can you please take a look?

**Comment by kbt1** [comment]
ID#43391 i can not email invoice, getting error message.
![image](https://user-images.githubusercontent.com/26387044/27916312-4f32a492-622e-11e7-8b2a-28a3ff4f4e2d.png)

**Comment by kbt1** [comment]
just noticed ID#43391 is current, not expired.

**Comment by kbt1** [comment]
good to go.
