### ISSUE TITLE
Posting Monthly Check Payments batch

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#212]
Sagar
I deleted the 2 transactions that were not approved for check payments in the Bulk Dues Batch.
I updated the amount and posted.
The 2 companies that I deleted their transactions, still got posted with an expiration date of 8/1/17.
I manually changed them back to their previous dates.

can you test and see if it happens to you?

**Comment by sagarjagdish** [comment]
@kbt1 : Please give me batch# and member# that need to be remove from that batch. I will remove that entry first and then look into further.

**Comment by kbt1** [comment]
Batch 7-1-17 Bulk Entry Check
ID#44071
ID#44259

i think they were deleted but still posted with current expiration date.
I changed expiration dates back so they are correct but please make sure they are not posted in the batch.

**Comment by sagarjagdish** [comment]
We have looked into this issue and found cause of this. Not it's resolved in stage and production both.

**Comment by kbt1** [comment]
I will be running another Check batch in 2 weeks, if I have any problems, i will let you know.

thank you
