### ISSUE TITLE
Printing invoices

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#215]
i selected these records which have Prosis due
![image](https://user-images.githubusercontent.com/26387044/27959574-a1721a48-62ed-11e7-830a-948aaf6152ec.png)

and prosis didnt print on invoices
[Invoices not printing Prosis due.pdf](https://github.com/omnitekinc/AERA_MSS_Clients/files/1131079/Invoices.not.printing.Prosis.due.pdf)

**Comment by sagarjagdish** [comment]
@kbt1 It's resolved on production. Please take a look and let us know if any query.

**Comment by kbt1** [comment]
printing membership and prosis is not printing and should!
[invoices still printing with membership only and should include Prosis.pdf](https://github.com/omnitekinc/AERA_MSS_Clients/files/1131384/invoices.still.printing.with.membership.only.and.should.include.Prosis.pdf)

**Comment by kbt1** [comment]
sorry, i logged out and logged back in and it is fixed.

good to go!
