### ISSUE TITLE
Prosis Pro Buffer Days

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#217]
Sagar
can you change the Buffer Days to 7 now for all records.

thank you!

**Comment by sagarjagdish** [comment]
@kbt1 
It's resolved on production. now Buffer Day set to 7 for all records.
![bufferdays](https://user-images.githubusercontent.com/7322922/28101854-dbe80d82-66e8-11e7-9bdb-55418ee0f004.png)

**Comment by kbt1** [comment]
thank you!
