### ISSUE TITLE
printing invoice 

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#218]
ID#248 both membership and prosis are due. when i select their record and print invoice, only membership prints.

![image](https://user-images.githubusercontent.com/26387044/28167090-f48e58b6-679f-11e7-8e29-c9045c08e014.png)

**Comment by sagarjagdish** [comment]
I just exported same invoice and it's showing both. I think there is something session conflict issue. That we need to check. If you can try now, It should will work.

![image](https://user-images.githubusercontent.com/7322922/28167596-bba2741a-67f9-11e7-8fbe-201789093008.png)

**Comment by kbt1** [comment]
Now only Prosis prints.
![image](https://user-images.githubusercontent.com/26387044/28167754-49a41442-67a2-11e7-803b-9f4706b38fc0.png)
and i get this error

![image](https://user-images.githubusercontent.com/26387044/28167779-5d6f6b70-67a2-11e7-88db-5379d74f8186.png)

**Comment by kbt1** [comment]
i signed out and signed back in and now it is fine.

this seems to happen a few times and every time i sign out and sign back in, things are fine.
last week i printed invoices and they were all wrong. when i logged out and back in, they were fine.
there must be some sort of issue.

**Comment by sagarjagdish** [comment]
We are looking into this. Please don't close this ticket until we address this issue.

**Comment by kbt1** [comment]
thank you

**Comment by kbt1** [comment]
i am still getting this error message also when i try to print invoice for ID#42837
![image](https://user-images.githubusercontent.com/26387044/28212623-e2008a2a-6867-11e7-9272-0f434d48729e.png)

**Comment by sagarjagdish** [comment]
@kbt1 : This member having too old expiry. Please refer below thread for this implementation.

https://github.com/omnitekinc/AERA_MSS_Clients/issues/197

https://github.com/omnitekinc/AERA_MSS_Clients/issues/186#issuecomment-306820485

https://github.com/omnitekinc/AERA_MSS_Clients/issues/86#issuecomment-298397673

**Comment by sagarjagdish** [comment]
We have found cause of only Membership and only Prosis Pro invoice generate issue and resolved that issue on production.

Now onward this issue will not be occur because of Session conflict.

**Comment by kbt1** [comment]
Can you add a button here to print Membership and Prosis on one invoice? This would work for expired members for what i need.  
![image](https://user-images.githubusercontent.com/26387044/28213644-9b777410-686c-11e7-87a1-3fab5160f0d6.png)

**Comment by sagarjagdish** [comment]
Yes, that we can. This button will generate Prosis Pro and Membership both in single invoice without considering any criteria like 90 days or too old expiry date, correct?

**Comment by kbt1** [comment]
Yes, that would be perfect.

**Comment by sagarjagdish** [comment]
@kbt1 : We have added print invoice button at top please refer below image and try with that.

![image](https://user-images.githubusercontent.com/7322922/28214877-a04cacf0-68c9-11e7-923a-2bc2e1d4c48b.png)

**Comment by kbt1** [comment]
that works perfect.
thank you!
i will keep you posted if I have any other issues with session conflict.
