### ISSUE TITLE
Adding Prosis to a new member

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#219]
I am trying to add prosis to a new member 
![image](https://user-images.githubusercontent.com/26387044/28229637-20a75dbc-68a9-11e7-9963-3607bb4ea27e.png)
and when i click on save, i get this
![image](https://user-images.githubusercontent.com/26387044/28229653-2e2b8c60-68a9-11e7-9cf5-015d6de3f223.png)
it wont save it. i signed out and back in and still did not work.

**Comment by sagarjagdish** [comment]
@kbt1
It's resolved on production. now you can add new prosis. 
Please take a look and let us know if any query.

**Comment by kbt1** [comment]
good to go
