### ISSUE TITLE
Membership - Start Date

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#22]
This is the same image I used for another error, you can see they expired in 1992:
![member record 12923](https://cloud.githubusercontent.com/assets/26386841/24060631/1ffb63e8-0b22-11e7-917a-8733ac62a7e7.JPG)
After I processed their dues I went back to the member record and at a glance I can see they've been members on and off since 1987, however the start date stayed at 11/1/1991 instead of updating to 3/15/17, so it looks like they've been a member constantly since 1991 instead of rejoining in 2017.

I literally just received an email from you about not doing the dues processing and invoicing yet, so if this falls into that just ignore. Thanks!

**Comment by omnitekinc** [comment]
Sagar, please take a look at this one.

**Comment by sagarjagdish** [comment]
I have looked and it's updated expiry date. logic it same as old software. expiry date update only once batch posted.

![image](https://cloud.githubusercontent.com/assets/7322922/24235744/a2a18c22-0fc4-11e7-86cd-90c323aa1a4d.png)

**Comment by amandagoyette** [comment]
It looks like this has been fixed.  May have been an issue with Batch not being ready to test.  I tested Mbr #15328 who expired in 2011.  Upon processing batch start and end date updated:
![image](https://cloud.githubusercontent.com/assets/26386841/24255637/0cefc5d2-0fb4-11e7-91c8-ef3443a746e4.png)
