### ISSUE TITLE
Monthly Report Tab

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#220]
New Membership Report 

I get this for FY2018
![image](https://user-images.githubusercontent.com/26387044/28337033-e3441e00-6bc9-11e7-9034-fa5906983d71.png)

I get this for FY2017
![image](https://user-images.githubusercontent.com/26387044/28337046-ed1f1114-6bc9-11e7-8132-65926c56e34c.png)

does each FY need to be set up for each year or can it be done in advance?

this is what i get if i enter 7/1/17
![image](https://user-images.githubusercontent.com/26387044/28337121-271fefb4-6bca-11e7-9b1a-a23829943fec.png)

**Comment by sagarjagdish** [comment]
@kbt1 : We have implemented this report as per below comment. Please let us know if any change required in this. Also please let us know if there is any wrong information exported in report so we can review and make it resolve.

++++++++++++++
Our fiscal year is July 1 thru June 30th. So we are currently in July 2016 thru June 30, 2017 Fiscal year.
++++++++++++++
https://github.com/omnitekinc/AERA_MSS_Clients/issues/150#issuecomment-303443729

**Comment by kbt1** [comment]
looks good. all info matches
