### ISSUE TITLE
State Names in Membership

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#24]
Can you list the Abbreviations of all the states instead of them Spelled out.

![image](https://cloud.githubusercontent.com/assets/26387044/24062384/5dba3856-0b29-11e7-9ecb-253dcad345a5.png)

**Comment by omnitekinc** [comment]
Hi Sagar, please update, here is your reference.
http://www.infoplease.com/ipa/A0110468.html

**Comment by sagarjagdish** [comment]
We done with abbreviations states code and uploaded on stage. Please verify and confirm.

**Comment by kbt1** [comment]
good
