### ISSUE TITLE
Membership-Additional Contacts

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#25]
The last name from Contact one is appearing as the last name for contact 2 and the titles do not show up:

"Edit" Screen view: 
![image](https://cloud.githubusercontent.com/assets/26386841/24062726/9a512418-0b2a-11e7-98b5-a1cee8597d27.png)

Member Screen View:
![image](https://cloud.githubusercontent.com/assets/26386841/24062755/b4fa9704-0b2a-11e7-8646-08eb5ad9932c.png)

Should say Accounting Guru, not Accounting One.  This was tested on member #44222

**Comment by sagarjagdish** [comment]
We have found cause and make it resolved on stage.

**Comment by amandagoyette** [comment]
Looks good.  Thanks!
