### ISSUE TITLE
Membership-Prospects-Search Function

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#26]
When you are in the prospects tab and try to use the search function it reverts to the member tab and only shows member search results.

**Comment by omnitekinc** [comment]
Sagar, can we make the search works in each section inside membership?

**Comment by sagarjagdish** [comment]
now it's working. please refer below image.

![image](https://cloud.githubusercontent.com/assets/7322922/24252707/3d95f274-1004-11e7-8d9e-9e16304efc4f.png)

**Comment by amandagoyette** [comment]
tested and it seems to be working properly.  Thanks!
