### ISSUE TITLE
Membership-Prospects-30 Day Trial

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#27]
Is there a reason the PROSIS PRO Demo users in the Prospect List cannot be edited?

**Comment by omnitekinc** [comment]
Sagar?

**Comment by kbt1** [comment]
there should be an edit function for Prosis demo users unders Prospects like all records

![image](https://cloud.githubusercontent.com/assets/26387044/24102487/27eb0b56-0d4a-11e7-96d7-c39c48056089.png)

**Comment by sagarjagdish** [comment]
@kbt1 : sure. We are already working on this and once it's done, I will update here.

**Comment by sagarjagdish** [comment]
@kbt1 : We have implemented edit function for for demo users and uploaded on stage.

**Comment by kbt1** [comment]
good.
