### ISSUE TITLE
Status box on Tech Que

### ISSUE THREAD

**Issue by robchar** [omnitekinc/AERA_MSS_Clients#28]
Would it be possible to move the status box on the tech que to the bottom of the page, or create a 2nd one.

**Comment by omnitekinc** [comment]
Hi Rob,
What is the thinking behind moving the status box? Can you please explain and I will come up with a solution.
Thanks,
Stella

**Comment by robchar** [comment]
Hi Stella,

The status box is the last thing that we do to finish the call which means we are at the bottom of the page. The way it is right now we are having to scroll back up the page in order to either choose close, new, or in process.

I hope that makes sense.

Thanks
Rob



Rob Munro

Membership & Technical Development

AERA Engine Builders Association

P: (815) 526-7345

F: (888) 329-2372

________________________________________

**Comment by omnitekinc** [comment]
got it!

**Comment by omnitekinc** [comment]
Sagar, can you make the status box at the bottom of the screen, also add the Save & Cancel button as well. 
<img width="179" alt="screen shot 2017-03-18 at 12 39 14 pm" src="https://cloud.githubusercontent.com/assets/7178461/24075403/0aa4733e-0bd8-11e7-9747-4d400562798d.png">
<img width="910" alt="screen shot 2017-03-18 at 12 39 31 pm" src="https://cloud.githubusercontent.com/assets/7178461/24075404/0aa4a566-0bd8-11e7-9315-17c0203cd0cc.png">

**Comment by sagarjagdish** [comment]
We have added status at the bottom of the page. Please verify and confirm.
