### ISSUE TITLE
Data type list located at the bottom of the Tech Que

### ISSUE THREAD

**Issue by robchar** [omnitekinc/AERA_MSS_Clients#29]
Can we please add and change the list that is located at the bottom of the tech que called Data Type to read as follows

PPro - ALLDATA - Mitchell - Bulletins - Diagram - Procedures/Process - Manual - Cummins - Internet - No Info

**Comment by omnitekinc** [comment]
Steve, just want to check with you if Rob's data type order works for you. If you are ok, we will update.

**Comment by stevefox3781** [comment]
In looking at the current version, it looks like it is the same other than "internet". I need some more explanation on why the internet would need to be listed before we proceed on this one. If we download a manual for the internet, to me you would check the Manual box.

**Comment by stevefox3781** [comment]
Stella, it is fine.

**Comment by omnitekinc** [comment]
Sagar, please update

**Comment by sagarjagdish** [comment]
We have updated "DataType" list as suggested and uploaded on stage. Please verify and confirm.

**Comment by stevefox3781** [comment]
Good to go.
