### ISSUE TITLE
Tech Queue Date & Time

### ISSUE THREAD

**Issue by stevefox3781** [omnitekinc/AERA_MSS_Clients#3]
Instead of having us enter the date & time of the call, would like it to read the computer for date & time. 

![date time](https://cloud.githubusercontent.com/assets/26387391/23916200/6f35469c-08b9-11e7-989b-c2fd8d1ef2a9.jpg)

**Comment by omnitekinc** [comment]
Sagar, please auto fill them based on the server or computer time.

**Comment by sagarjagdish** [comment]
We have populate from as per sever time and uploaded this change on stage. Please verify and confirm.

**Comment by stevefox3781** [comment]
Works great!
