### ISSUE TITLE
Phone # format in Membership

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#30]
Can you have the phone and fax fields automatically format the numbers like this
888-326-2372 so we just enter numbers and the field formats it.

Like below:

![image](https://cloud.githubusercontent.com/assets/26387044/24103186/77102516-0d4c-11e7-950a-f130e4da0dea.png)

**Comment by sagarjagdish** [comment]
@kbt1 : actually we did such formatting but it was working after save data :) . We have implemented function to format phone# and Fax# at the time of entering date. Please verify and confirm.

**Comment by kbt1** [comment]
looks good.
