### ISSUE TITLE
Dues not updating membership exp date

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#31]
I processed 2 dues, 1 for a full year and 1 that was a 6 month renewal.
Only the full year renewals expiration date got updated after I posted.

This record didnt:  
![image](https://cloud.githubusercontent.com/assets/26387044/24103824/823ee18c-0d4e-11e7-8f9a-4647e4ea26b1.png)

here is the dues batch that posted

![image](https://cloud.githubusercontent.com/assets/26387044/24103871/a351d2e4-0d4e-11e7-81df-34d57eaa787e.png)

**Comment by omnitekinc** [comment]
Hi Karen, Due Processing is not ready for testing yet. I will let you know when it's ready.
