### ISSUE TITLE
Prosis Pricing

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#32]
Stella
Where do we set up Prosis Pricing so I dont have to pull up each record and enter the new fee for invoicing like CMS?  Thought it would be like dues pricing.

**Comment by omnitekinc** [comment]
Hi Sagar,
We are supposed to have the 6 Prosis Pro pricing at the bottom of setting/pricing, where did it go?

**Comment by sagarjagdish** [comment]
uploaded Prosis pro price section on stage under "system setting" tab.  Please see below image for reference.

http://71.13.159.202/aeramms_stage/systemsetting.aspx

![image](https://cloud.githubusercontent.com/assets/7322922/24296115/b81655ec-10c3-11e7-9dc8-ce6639adb765.png)

**Comment by kbt1** [comment]
good.
