### ISSUE TITLE
Conferences

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#33]
Under conferences, it lists exhibitors and attendees under 1 list. Can you add 2 buttons
"Exhibitor" "Attendee" so if we click on one, it only brings up the list for that selected with a count of each.
Each attendee and additional attendee should show up for each company and same with each exhibitor name and additional name should show up. We need a complete list we can view.

![image](https://cloud.githubusercontent.com/assets/26387044/24117502/7ff7c93c-0d78-11e7-97ec-d19200d20e4d.png)

**Comment by omnitekinc** [comment]
Sagar, please add a filter for All, exhibitor, attendee

**Comment by sagarjagdish** [comment]
I have added filter option for ALL,  exhibitor, attendee, Non Member exhibitor. I also changed view of listing screen to see which give batter view to for main attendee with additional attendee. If there is any change in listing then please let me know, I just tried to make it easy for AERA.

http://71.13.159.202/aeramms_stage/attendeelist.aspx?id=19&mode=edit&type=0&state=&year=0&month=0&lastopentab=U&page=1&historypage=conferences.aspx 

<img width="765" alt="attendee_list" src="https://cloud.githubusercontent.com/assets/7322922/24234331/bfab89aa-0fbd-11e7-92e4-3342e6079217.png">

**Comment by kbt1** [comment]
good.
