### ISSUE TITLE
Conference Registration

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#37]
When registering an exhibitor under ID#44217, Steve Fox and AERA come up....

![image](https://cloud.githubusercontent.com/assets/26387044/24150779/c47de464-0e14-11e7-8adc-0b10a180f27a.png)

Not sure on this:  Email can not be a required field for exhibitors or attendees, there are times attendees dont have email or dont supply an email so i would mail a confirmation letter.

**Comment by kbt1** [comment]
Ignore Steve Fox, AERA coming up under #44217.

**Comment by omnitekinc** [comment]
Sagar, please make Email not a required field.

**Comment by sagarjagdish** [comment]
now onward email not required in conference registration. It's uploaded on stage. please verify and confirm.

**Comment by kbt1** [comment]
good.
