### ISSUE TITLE
Membership - Address - Address 2 not visable

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#38]
Our old system has address 1 and address 2 fields.  
![image](https://cloud.githubusercontent.com/assets/26386841/24151472/dec53ec4-0e16-11e7-8278-593ecb76583a.png)

This just has one.  On this member (#99) I see the highlighted PO Box, but when I go to edit it doesn't exist.  
![image](https://cloud.githubusercontent.com/assets/26386841/24151440/c565bd1e-0e16-11e7-897f-de77dd91f051.png)

We need to be able to see that address 2 box and edit it.

**Comment by omnitekinc** [comment]
Sagar, can you take a look, it's very strange, in edit mode PO BOX 1884 doesn't show, only 123 test road. 

![screen shot 2017-03-21 at 9 58 08 am](https://cloud.githubusercontent.com/assets/7178461/24159704/004ccae8-0e1d-11e7-9018-85314203bec0.png)

**Comment by sagarjagdish** [comment]
I have merge address 1 and 2 with simple address field and now you can see both within single text area. 

![image](https://cloud.githubusercontent.com/assets/7322922/24252999/1235723e-1005-11e7-9a6d-7d11f6caff95.png)

**Comment by amandagoyette** [comment]
@kbt1 what are your two cents?  Do you think it works having it all in one field or should we have an address 1 and address 2?  We can talk in tomorrow's meeting if needed.  My one concern is pulling lists for mailings.  Anything over 50-60 characters risks getting chopped off.

**Comment by amandagoyette** [comment]
Follow up on this one.  Upon looking at the export reports, for the mailing address at least, we need Address 1 and address 2 to have their own boxes.  
When we go to do a mailing everything exports into 1 field in the file and there's no way we can be certain the address doesn't get cut off when we go to mail to members if we don't split it.  Here's an example (mbr 44154):
![image](https://cloud.githubusercontent.com/assets/26386841/24306446/9a561e3c-108e-11e7-9f45-5aebad56abf9.png)

**Comment by kbt1** [comment]
This is very important with International addresses. Some are so long they roll over into the address 2 field so each field must be its own column when pulling a report.

**Comment by sagarjagdish** [comment]
We have added address 1 & address 2 text box in add/edit member ship screen. Please verify and confirm.

**Comment by omnitekinc** [comment]
Amanda, can you please verify this and close the ticket. Thanks!

**Comment by amandagoyette** [comment]
looks good thanks!
