### ISSUE TITLE
Membership - Addresses

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#39]
We don't need a period after the zipcodes.  Can we remove it?  

![image](https://cloud.githubusercontent.com/assets/26386841/24152026/67cdacdc-0e18-11e7-87a6-304fabb17227.png)

**Comment by sagarjagdish** [comment]
removed period after the zipcodes also taken related action suggested under below https://github.com/omnitekinc/AERA_MSS_Clients/issues/41
