### ISSUE TITLE
Tech Queue - Duplicate Call

### ISSUE THREAD

**Issue by stevefox3781** [omnitekinc/AERA_MSS_Clients#4]
When you create a new call, if the member has two questions, there is no way to Duplicate the membership information into a new call. The duplicate button is available if you take a call from the queue, but not when you create a new call. We need the ability to duplicate a call from a new call as well. I have included two screen shots, one of creating a new call and one from a call already in the queue. Any questions, let me know. 

![create new call](https://cloud.githubusercontent.com/assets/26387391/23949211/6320fe6e-0954-11e7-9a06-a274598a8467.jpg)
![duplicate call](https://cloud.githubusercontent.com/assets/26387391/23949216/6537339e-0954-11e7-9a8d-d6e03c1d5a66.jpg)

**Comment by omnitekinc** [comment]
Hi Sagar,
It is possible to add a "duplicate" button inside the editing screen, and when AERA click, it open a new browser window with a new duplicate Tech Call. 
![6320fe6e-0954-11e7-9a06-a274598a8467](https://cloud.githubusercontent.com/assets/7178461/23964500/f662fdea-0971-11e7-952c-b405220f187d.jpg)

**Comment by sagarjagdish** [comment]
We have added duplicate button in add screen which shows before click on save as per suggested by Stella and after click on save AERA can see non edited version of Tech Call with duplicate button as shown below. Please verify once by adding new tech call and let us know if any change required in this.

<img width="779" alt="duplicate_in_add_new_call" src="https://cloud.githubusercontent.com/assets/7322922/24080111/1fd044e0-0cbe-11e7-8944-8ae9221da08b.png">

**Comment by stevefox3781** [comment]
That will work. I will have the other techs check it out and report.
