### ISSUE TITLE
Prosis

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#42]
Stella, can you pull the Notes out of Prosis Pro CMS under account info?

![image](https://cloud.githubusercontent.com/assets/26387044/24169352/564f433e-0e4b-11e7-8bce-f152ecc64b20.png)

**Comment by kbt1** [comment]
You have click on "edit" to see the notes, can you have them appear under membership comments and mark them as Prosis Pro Notes.

**Comment by omnitekinc** [comment]
Hi sagar,
Can we move the Prosis Pro notes under comments?

![screen shot 2017-03-22 at 6 54 52 pm](https://cloud.githubusercontent.com/assets/7178461/24228411/4438ebe6-0f31-11e7-8047-abad9bc75319.png)

**Comment by sagarjagdish** [comment]
We shown prosis pro notes at bottom after comment section, however for add/edit member option it's showing under prosis pro region with other prosis pro information. see below image for view/add/edit option. Please let me know if any change required in this.

![image](https://cloud.githubusercontent.com/assets/7322922/24253190/9eee5a4c-1005-11e7-9b15-91da74e9418a.png)

**Comment by kbt1** [comment]
good
