### ISSUE TITLE
Membership - Search

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#44]
I'm not sure if the search by date range is not working or if I don't understand how it's set up.  I think we may need to discuss the searches for reports and membership as I'm not sure they're in a format that works well for our needs.  

I think, maybe, the reports are searching based on the Join Date (this is a guess, I am not certain) and cannot for the life of me figure out the membership date range search. I keep getting 0 results

![image](https://cloud.githubusercontent.com/assets/26386841/24170072/a6338584-0e4d-11e7-8baf-e1dc18360e5b.png)

**Comment by omnitekinc** [comment]
Hi Amanda,
Let's discuss this on our call on Friday.
Stella

**Comment by sagarjagdish** [comment]
@omnitekinc  : I have added comment for your reference for the logic of membership search function. It's working based on join date.

Start Date : 01-01-2010
End Date :  [#Empty]
If you put Start Date 01-01-2010 then it's show all the users having Join Date 01-01-2010 and greater than 01-01-2010 as end date it blank.

Start Date : 01-01-2010
End Date : 31-01-2010
If you put Start Date 01-01-2010 and End Date 31-01-2010 then it will show only those users who joined between that date.

Start Date : [#Empty]
End Date :  31-01-2010
If you put only End Date 31-01-2010 then it will show all the users who joined before 31-01-2010 date as Start Date blank.

**Comment by omnitekinc** [comment]
Amanda, does the date range search make sense? Is there anything thing you would like to update?

**Comment by amandagoyette** [comment]
Hey Stella, I understand now it's based on the Join Date, but I think we need to be able to search by expiration date.  I'm reaching out to @kbt1 and getting her two cents.  I'll make sure this is updated after we've discussed.

**Comment by amandagoyette** [comment]
Stella, lets discuss this in the meeting tomorrow.

**Comment by amandagoyette** [comment]
We discussed the fix for this yesterday.  Not sure if you started a separate ticket Stella, so I'm assigning to you so you can close if needed otherwise I'll leave it open until that update is in place :)

**Comment by omnitekinc** [comment]
I created a new ticket for this fix, will close this for now.
