### ISSUE TITLE
Status box on tech que moves back up the page after hitting the save button

### ISSUE THREAD

**Issue by robchar** [omnitekinc/AERA_MSS_Clients#48]
The status box is at the bottom of the page of the tech que until you click the save button. Then it is gone and moves back up to the top of the page. If you could keep it down at the bottom of the page for all functions.

**Comment by omnitekinc** [comment]
Sagar, can we keep the placement of the status box at lower left after save.

**Comment by sagarjagdish** [comment]
We done with this change and uploaded on stage. please verify and confirm.
