### ISSUE TITLE
Membership/additional contact

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#49]
We need a space between title and first name on the additional contacts:
![image](https://cloud.githubusercontent.com/assets/26386841/24257076/dacacb5c-0fb7-11e7-8c90-bfd80605c2c8.png)
Mr. James Rickoff instead of Mr.James Rickoff

**Comment by sagarjagdish** [comment]
added space between title and first name on the additional contacts:

![image](https://cloud.githubusercontent.com/assets/7322922/24297217/f384af3a-10c7-11e7-9743-ce49c9476f21.png)

**Comment by amandagoyette** [comment]
thanks!
