### ISSUE TITLE
Response area mispelling

### ISSUE THREAD

**Issue by chulynch** [omnitekinc/AERA_MSS_Clients#5]
Cummins is mis-pelled. 

![mis spelling](https://cloud.githubusercontent.com/assets/26386865/23956047/a419c954-0969-11e7-8e88-ce99e1f2e0e2.JPG)

**Comment by sagarjagdish** [comment]
We corrected that spelling, please refer below image for reference.

<img width="774" alt="tech-call-mispelling" src="https://cloud.githubusercontent.com/assets/7322922/24010303/7966e090-0a9d-11e7-8094-381b435a309c.png">

**Comment by omnitekinc** [comment]
Hi Chuck,
Please review, and if you approve this update, please close this ticket. 
Stella

**Comment by chulynch** [comment]
Good to go. Thank You
