### ISSUE TITLE
Conferences - Export

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#51]
When I do an export of Exhibitors, it comes up with no info found

![image](https://cloud.githubusercontent.com/assets/26387044/24264967/000959fc-0fd0-11e7-9e7d-eeb7a134e25b.png)

![image](https://cloud.githubusercontent.com/assets/26387044/24265026/2a37a2ba-0fd0-11e7-954d-18bcec847997.png)
and before you can even check and make sure you are pulling the correct data, it resets everything to Attendee type all and conferences all.

**Comment by sagarjagdish** [comment]
@kbt1 : There is one issue with export function that we resolved and uploaded on stage by today. Please verify and confirm.

**Comment by kbt1** [comment]
ok
