### ISSUE TITLE
Conference Tab - Export 

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#54]
Can you remove Column A, B & C and Make a 1 Line header of the Conference Name at the top.

![image](https://cloud.githubusercontent.com/assets/26387044/24308744/3e0365be-1097-11e7-9923-30170d0c9581.png)

**Comment by sagarjagdish** [comment]
@kbt1  : I have attached one sample format will that work for you? Please provide your feedback so we can implement.

[Attendee History - 03-30-2017_5900.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/881875/Attendee.History.-.03-30-2017_5900.xlsx)

**Comment by kbt1** [comment]
remove column A, F, H

order for columns should be:
Registration type, Member #, Contact Name, Company Name, Address 1, Address 2, City, State, Zip, Country, Ph#, Email, Total Paid, Confirmation

can you have it so exhibitors are first and then attendees are listed after alphabetically by company name.

**Comment by sagarjagdish** [comment]
We have uploaded this change on stage. please export report and let me know if any change required.

**Comment by kbt1** [comment]
Tried this export for SRI regional attendees and got this message

![image](https://cloud.githubusercontent.com/assets/26387044/24662774/b55dbd30-191b-11e7-8877-990896d68c66.png)

**Comment by sagarjagdish** [comment]
@kbt1 : This message shown only because we have generated excel through code and did some custom operation related to format. You simply need to click on "Yes" to open that excel.

Please click on Yes to open this excel and let me know if any change required in format.

**Comment by kbt1** [comment]
I have made a changes, see highlighted changes.

*I would like a total for exhibitor income
*I would like a total for attendee income
**can you make non member exhibitors show up on list with exhibitors, not attendees.

[Attendee History - 04-04-2017_2900 (2) fix.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/893719/Attendee.History.-.04-04-2017_2900.2.fix.xlsx)

**Comment by sagarjagdish** [comment]
We have updated report as per your required. Please verify and confirm.

**Comment by kbt1** [comment]
looks good.
