### ISSUE TITLE
Add option in Tech Calls

### ISSUE THREAD

**Issue by chulynch** [omnitekinc/AERA_MSS_Clients#55]
See image. Add Custom Training in Tech Calls drop down
![custom training request](https://cloud.githubusercontent.com/assets/26386865/24311834/dbbb8762-10a3-11e7-87a3-da29defddf84.jpg)

**Comment by sagarjagdish** [comment]
added Custom Training in Tech Calls drop down.

![image](https://cloud.githubusercontent.com/assets/7322922/24501148/f05acac2-1565-11e7-92cf-73a777c8d178.png)

**Comment by chulynch** [comment]
looks good. Thank you
