### ISSUE TITLE
Add PDF File to call

### ISSUE THREAD

**Issue by stevefox3781** [omnitekinc/AERA_MSS_Clients#56]
Sometimes we will fax inforamtion to a member instead of emailing it to them. We need the option to add the PDF file faxed to the call. Please add this option shown in the screen shot attached
![add pdf file to call](https://cloud.githubusercontent.com/assets/26387391/24312047/ce62665c-10a4-11e7-9951-fd8ab7665cfa.jpg)
.

**Comment by sagarjagdish** [comment]
added option to upload PDF when response option selected as Fax. It will shows like below. provided option to upload multiple files and with view history same as email.

![image](https://cloud.githubusercontent.com/assets/7322922/24501270/676ded2e-1566-11e7-89d3-beed48c88ac3.png)

**Comment by omnitekinc** [comment]
steve please verify and close the ticket.

**Comment by stevefox3781** [comment]
All working good.
