### ISSUE TITLE
Tech Queue Closed Call Search

### ISSUE THREAD

**Issue by stevefox3781** [omnitekinc/AERA_MSS_Clients#57]
We need the ability to search the closed calls better. I like the options that are there, but we need to drill down more, especially when searching engines. Would it be possible to take this info 
![image](https://cloud.githubusercontent.com/assets/26387391/24312176/5bf9390a-10a5-11e7-82a4-7b580fc13e2d.png)
and add it to the closed call search? This would narrow down to the engine directly. From that, we would need the ability to search by a key word or phrase from the engine search results and see that results. Or we can add the word(s) search box at the end then you will get the results that you want. 

I hope this makes sense if you have any questions, feel free to contact me.

**Comment by omnitekinc** [comment]
Sagar, is it possible?

**Comment by sagarjagdish** [comment]
@omnitekinc : Yes, working on that and once it's done will upload on stage.

**Comment by sagarjagdish** [comment]
We have added search by option in Tech call. Please refer below image. Please verify and let me know if any change required.
 
![image](https://cloud.githubusercontent.com/assets/7322922/24501664/1b1e22ac-1568-11e7-9070-47bee2236f5a.png)

**Comment by stevefox3781** [comment]
Works
