### ISSUE TITLE
Membership-Alternate Phone #

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#59]
The Alternate Phone number needs to be listed in membership.  It appears to be on the reports, but it's not viewable in membership.
Old System:
![image](https://cloud.githubusercontent.com/assets/26386841/24313547/3c48697c-10ab-11e7-9947-33b1a2f2cec5.png)

New System:
![image](https://cloud.githubusercontent.com/assets/26386841/24313562/52bf8802-10ab-11e7-8ebb-4a76133d6674.png)

**Comment by omnitekinc** [comment]
Hi Karen,
We removed the Alt phone number because we added the 2nd and 3rd contact. But if you need to add the Alt Phone, we can add it back, just not sure how often it's being use.

**Comment by amandagoyette** [comment]
Stella, Karen is out today, but will be back tomorrow.  I'll wait for her two cents.  These days it's more of a spot for a cell number for small shops.  Maybe we call it Cell number instead of Alt number?  We'll see what Karen thinks.

**Comment by kbt1** [comment]
Can you add Alt Phone to membership. I know we have additional contacts, but this alt number is some times a cell or an 800 number so i would add it back in as "Alt Phone"

**Comment by sagarjagdish** [comment]
added Alt Phone to membership. Please refer below image.

![image](https://cloud.githubusercontent.com/assets/7322922/24502172/47892fec-156a-11e7-979a-5e2d51475af9.png)

**Comment by kbt1** [comment]
looks good
