### ISSUE TITLE
Membership Type Drop Down Box

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#6]
![image](https://cloud.githubusercontent.com/assets/26387044/23969565/e7ceb5a8-0994-11e7-9a9f-326aca30e906.png)

Can this be changed to when you select Active or Engine Installer the types are only:
non US 1-3 Shop Personnel (G1)
non US 4-8 Shop Personnel
non US 9-24 Shop Personnel
non US over 25 Shop Personnel
US 1-3 Shop Personnel  (B1)
US 4-8 Shop Personnel
US 9-24 Shop Personnel
US over 25 Shop Personnel

For Associate Non US and US:
Agent, MR, BP (B1/G1)
0-$1M Sales (B2/G2)
$1-$3M Sales (B3/G3)
Over $3M Sales (B4/G4)

So when you pull the type down for Active and Engine Installer, it does not include Associate.
When you pull the type for Associate, it does not include Active.
Only Types that apply to the Class should come up.

(call me if you have questions on this)

**Comment by sagarjagdish** [comment]
Hi 

We updated member type as suggested, please verify and confirm. 

<img width="764" alt="member-type-change" src="https://cloud.githubusercontent.com/assets/7322922/24010013/9c02c976-0a9c-11e7-81d6-c7a4041e8ef0.png">

Please let me know if any change required in this.

**Comment by kbt1** [comment]
![image](https://cloud.githubusercontent.com/assets/26387044/24016895/d9e5ea70-0a5b-11e7-8cf5-55a7023be1a3.png)

can you remove US (B) or is that for something?

**Comment by kbt1** [comment]
For associate class types, can you add
US before each one B1-B4
NON US before each one G1-G4

Exactly like active so all types are consistent.

**Comment by sagarjagdish** [comment]
We removed US (B). We have added only for the testing purpose. Also added US before B1-B4 and NON US before G1-G4.

Please verify and confirm.

**Comment by kbt1** [comment]
looks good.
