### ISSUE TITLE
Membership - How to mark out of business

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#60]
Is there a way to mark a company out of business so they can eventually be archived/removed from the system?

**Comment by kbt1** [comment]
We need a mail code box like our old system with options- see image.

![image](https://cloud.githubusercontent.com/assets/26387044/24314019/74506368-10ad-11e7-93bb-17e770bdfdda.png)

**Comment by amandagoyette** [comment]
Thanks Karen!

**Comment by omnitekinc** [comment]
Sagar, can you add the mail code where I indicate in the image below.

![screen shot 2017-03-24 at 6 48 40 pm](https://cloud.githubusercontent.com/assets/7178461/24318448/b6744d08-10c2-11e7-8c6f-83444edcc659.png)

**Comment by sagarjagdish** [comment]
Hi Stella,

Okay, I will add such option but once AERA select such option, where should I have to list such user. I am which action required one AERA select any mail code and cancel subscription. Is there any specific action required?

**Comment by omnitekinc** [comment]
Hi Sagar,
Once AERA selected the mail code, the member should just stay inside membership but showed as expired with the mail code reason.

**Comment by kbt1** [comment]
The mail code box is for internal use only

**Comment by kbt1** [comment]
Can you take out:  Do Not Print Label  - this does not apply any longer.

**Comment by kbt1** [comment]
works perfect
