### ISSUE TITLE
Invoicing

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#61]
Stella
Since you had mentioned you are working in invoicing and dues, i wanted to send you a note:

For dues and prosis invoicing, i would like invoices to print Annual AERA Membership Fee or Annual Prosis Pro Subscription Fee, same with 6 Month AERA Membership Fee, 6 Month Prosis Pro Subscription Fee.

Monthly invoices do not need to be printed.

**Comment by sagarjagdish** [comment]
We have implemented function to stop email and print invoice for those users who having monthly payment type. 

however if you want to print/email invoice individually for those member system will allow with one warning message like "Member# 1234 having monthly payment plan, do you still want to continue with print/email invoice?"

Please review update and let me know if any change required in this.

**Comment by kbt1** [comment]
this works good.
