### ISSUE TITLE
Membership Tab - edit a record

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#63]
the box next to discount amount should read Discount Code, dont know if the box is too small and the e isnt showing up.

![image](https://cloud.githubusercontent.com/assets/26387044/24314285/d889ed6c-10ae-11e7-8723-30e7ee1bce8d.png)

**Comment by omnitekinc** [comment]
The box is too short and it got cut off. Sagar, please make the box longer.

**Comment by kbt1** [comment]
looks good
