### ISSUE TITLE
Log-in

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#64]
Stella, I cannot log in to the Membership Management System
Username: AH
Password: test123
I get this message:
![image](https://cloud.githubusercontent.com/assets/26386841/24411551/c4797fbe-139b-11e7-85c2-8505fba1518d.png)

**Comment by sagarjagdish** [comment]
@aharmening : Please try again. now it should work. by mistake your user removed from the database I just restored that user.

**Comment by amandagoyette** [comment]
I'm in Thanks Sagar
