### ISSUE TITLE
Dues Processing Report

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#68]
I need to print a report that shows the batch of dues entered like this:
[Dues Batch Report.pdf](https://github.com/omnitekinc/AERA_MSS_Clients/files/880034/Dues.Batch.Report.pdf)
this report matches batch 3-29-17KT that i created today. this is exactly what i need.
Maybe put a print report button at the bottom by the Post Button.
I can print the report and verify and then post.

**Comment by sagarjagdish** [comment]
We have uploaded this change on stage. Please verify and confirm.

**Comment by kbt1** [comment]
looks good.
