### ISSUE TITLE
Change layout of Membership Record

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#7]
![image](https://cloud.githubusercontent.com/assets/26387044/23970702/d07d58ce-0998-11e7-8239-aaf535877832.png)

Can you rearrange the membership screen to make the flow better:

Company Name
Prefix  First Name  Middle Name  Last Name
Position/Title
Mailing Address
Shipping Address
Phone  Fax  Email   Website
Category Code    # of Employees
Additional Contacts
Comments

**Comment by sagarjagdish** [comment]
Hi,

We changed layout of Membership, please refer below image.

![membership-screen](https://cloud.githubusercontent.com/assets/7322922/24009885/40fd8caa-0a9c-11e7-9481-c1e8e8335864.png)

**Comment by kbt1** [comment]
Looks good.
