### ISSUE TITLE
Dues Processing - entering Prosis Payment

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#70]
When entering a dues batch for Prosis, when you select Prosis Pro, it needs to take out type from Membership and pull type from Prosis Pro and amounts that match. The discount box blanks out too and I should be able to apply a discount to Prosis also.      See below:

![image](https://cloud.githubusercontent.com/assets/26387044/24472186/6abc56c8-148a-11e7-9d9c-295bc66d241d.png)

**Comment by sagarjagdish** [comment]
We have added discount filed for Prosis Pro users also did same change in add/edit membership screen to show that discount.

![image](https://cloud.githubusercontent.com/assets/7322922/24710089/ab67f4f2-1a39-11e7-845f-88562a2f67da.png)


![image](https://cloud.githubusercontent.com/assets/7322922/24708937/fddfcca4-1a35-11e7-8dab-ba143e22c6e7.png)

**Comment by kbt1** [comment]
When i change Reg Type to Prosis Pro and Type field, the amount due does not change for me.
Can you also widen the due amount box.

![image](https://cloud.githubusercontent.com/assets/26387044/24715072/f07664ba-19ef-11e7-8b1a-d7c0cf604d2f.png)

**Comment by sagarjagdish** [comment]
When i change Reg Type to Prosis Pro and Type field, the amount due does not change for me.
**=> found issue with code and resolved now.**

Can you also widen the due amount box.
**=> done with due amount box.**

Please verify and confirm above changes.

**Comment by kbt1** [comment]
works good
