### ISSUE TITLE
Printing Dues or Prosis invoice

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#73]
I noticed that the State is spelled out on the invoice but in the system they are abbreviated with 2 letters. It should be the 2 letter abbreviation on the letter too.  (I know this isnt complete yet)

**Comment by sagarjagdish** [comment]
We have taken action on stage to shown State with 2 letters abbreviated. Please verify and confirm.

**Comment by kbt1** [comment]
looks good
