### ISSUE TITLE
Conferences

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#75]
state field should be 2 letter abbreviations, not spelled out.

![image](https://cloud.githubusercontent.com/assets/26387044/24476601/89767648-1499-11e7-9c21-b5209b27ee46.png)

**Comment by sagarjagdish** [comment]
We have taken action and shown 2 latter State in dropdown list. Please verify and confirm.

**Comment by kbt1** [comment]
good.
