### ISSUE TITLE
Prosis Pro Expiration Date

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS_Clients#77]
Right now if the member's Prosis Pro expired, they can't login to Prosis Pro. Which is good, but what happen is, the account will only be activated if they pay. And Karen sometimes will take the payment in the morning, but she is work on a batch and don't close it until the end of the day, so the member gets a bit mad that their account is not activated instantaneously. So AREA is wondering if they can go in and change the Prosis pro expiration date manually in case they run into this scenario.

**Comment by sagarjagdish** [comment]
@omnitekinc  : it's already working. I have checked and change exp for one for the person from Membership add/edit screen and it's working fine.

1) One Prosis Pro member expired before 1 month.
2) Update Exp date of Prosis Pro from AERA MMS >> Add/Edit Membership screen.
3) Try to do login with that user and it's work for me.

Please let me know if any other case required to check.

**Comment by omnitekinc** [comment]
karen, can you please check on this one.

**Comment by kbt1** [comment]
Works good.
