### ISSUE TITLE
Membership expiration date to 1st

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS_Clients#78]
Can you set all expiration date to the 1st for new members, and also give Karen the ability to edit the expiration date if she needs to. And for renew member, just keep it as is. But also make sure Karen can edit the expiration date on the renew member

**Comment by sagarjagdish** [comment]
set exp date to 1st for new member on dues screen. also exp date is editable so any one change change exp date before post batch. also exp data can be change from the add/edit membership screen. please verify change on stage and let me know if any issue.

**Comment by omnitekinc** [comment]
Karen can you please verify

**Comment by kbt1** [comment]
works good
