### ISSUE TITLE
User Privilege 

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS_Clients#79]
Hi Sagar,
Can we set it up so only Steve, Kaen and Jim can view the due processing tab?

Also, only Jim, Steve, Karen and Amanda should have access to Account Settings. 

Stella

**Comment by sagarjagdish** [comment]
We have done with access implementation. Please see below screen where you can set access for member.

N/A = screen not visible. 
Full = Read/Add/Update/Delete/Open 
Update = Read/Update/Delete/Open 
Read = Open + View data (with non editable screen). 
Open = Only can open screen not able to do any thing else 

http://71.13.159.202/aeramms_stage/employeedetails.aspx?Empid=1

![image](https://cloud.githubusercontent.com/assets/7322922/24956608/0a279af8-1fa6-11e7-8994-a2a310095b9e.png)

**Comment by omnitekinc** [comment]
Karen, please verify.

**Comment by kbt1** [comment]
looks good.
