### ISSUE TITLE
Closed Call Search

### ISSUE THREAD

**Issue by stevefox3781** [omnitekinc/AERA_MSS_Clients#80]
The addition of the engine search in closed calls is great. We need the ability to search within those closed calls by a keyword or phrase. Can we select the engine, add the keyword or phrase and then hit search? Can we look at moving the SEARCH CLEAR Buttons after the search box. 

Also in the closed calls results, the results will need to be newest to oldest - newest being listed first. 

![closed call search](https://cloud.githubusercontent.com/assets/26387391/24659285/d3cc4868-1911-11e7-9214-6bc88d0d9a5d.jpg)

**Comment by omnitekinc** [comment]
Sagar, can we add a text field for keyword search? It should be keywords within the dropdown criteria

**Comment by sagarjagdish** [comment]
can we add a text field for keyword search? It should be keywords within the dropdown criteria
**=> added function to search by. please verify and confirm.**

Also in the closed calls results, the results will need to be newest to oldest - newest being listed first.
**=> currently we are showing recent closed call first. please let me know if any change required in this order.**

**Comment by stevefox3781** [comment]
The closed call order seems to still not be working properly. I agree the most recent calls closed should be listed first. In the example provided, the dates are all over and in no specific order. 

![closed call order](https://cloud.githubusercontent.com/assets/26387391/24969728/5320abfc-1f77-11e7-8201-0581fbda2dfb.jpg)

The keyword search seems to be working properly.

**Comment by sagarjagdish** [comment]
@stevefox3781 : Date which you highlighted it's Call Date not a Close Call date. 

Ex : We can see Call with date 08/10/2016 at first because it's most recent closed call, here 08/10/2016 it Call Date not Close Date. 

I think we need one more column in close call tab name with "Close Date", where we can see close call date time. 

Please let me know your thoughts.

**Comment by omnitekinc** [comment]
Hi Sagar,
Can we order the closed calls by the close date, the latest should be on the top.

**Comment by sagarjagdish** [comment]
already we are order by closed date but to avoid confusion we have added call date and close date column as below. Please review and let us know if any query.
 
![image](https://cloud.githubusercontent.com/assets/7322922/25289757/941a73f4-26e8-11e7-960d-59e97e6cb32c.png)

**Comment by stevefox3781** [comment]
Looking good!
