### ISSUE TITLE
Product Invoice

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#81]
Stella
This looks good so far. Can you make my email the default for the "to" box

also, Membership and Prosis need to be added to the list for Products. We take a lot of membership and prosis renewals over the phone.

**Comment by omnitekinc** [comment]
Hi Sagar, can you add membership & prosis Pro info to the order form.
![screen shot 2017-04-04 at 9 32 19 am](https://cloud.githubusercontent.com/assets/7178461/24668007/31c32e70-191a-11e7-8b53-1a41d9da829c.png)

**Comment by kbt1** [comment]
Can we make it simpler and just type Membership and enter a fee or Prosis and enter a fee.
Not everyone who takes renewals know all the fee structures. This way when i process it, i can process the correct way in Dues. unless it is easier this way.

**Comment by omnitekinc** [comment]
Ok, do you want the dropdown? Or just ability to type in the membership?

**Comment by kbt1** [comment]
How about just the ability to type in Membership or Prosis and if they know the amount, they can fill it in and if not leave it blank.

**Comment by sagarjagdish** [comment]
We have added 2 text box as per below image, where you can type Membershi or ProsisPro and if fees available for that member then it will auto populate in fees text box. Please review change and let me know if any other change required on this required.

![image](https://cloud.githubusercontent.com/assets/7322922/24788142/7e3bc458-1b89-11e7-8f17-37d86fde0f52.png)

**Comment by kbt1** [comment]
Stella
Can you add Membership and Prosis Pro to the the Items Dropdown box and we can fill in the prices.
I tried doing a membership or prosispro in the boxes supplied and got this below, its looking for an item number.  It doesnt need to autofill pricing.



![image](https://cloud.githubusercontent.com/assets/26387044/24802828/f18a7f6e-1b6e-11e7-9a6e-b1248826f9c6.png)

**Comment by kbt1** [comment]
one more thing, can you make it a larger screen so we dont have to scroll up and down.

**Comment by omnitekinc** [comment]
Sagar, can we add the following to the screen.

![screen shot 2017-04-10 at 1 55 13 pm](https://cloud.githubusercontent.com/assets/7178461/24882703/de914548-1df6-11e7-851d-2f5a6f7e35c8.png)

**Comment by kbt1** [comment]
that would be good Stella.

**Comment by kbt1** [comment]
this is exactly how i would like this to look - perfect Stella


![image](https://cloud.githubusercontent.com/assets/26387044/24968096/bf175258-1f71-11e7-866d-d97b40ed013f.png)

**Comment by sagarjagdish** [comment]
implemented function as suggested and include Membership & Prosis Pro in email as well. Please verify on stage and let me know if change.

![image](https://cloud.githubusercontent.com/assets/7322922/25045427/fb29b2ca-2149-11e7-9581-f646e17afccb.png)

**Comment by kbt1** [comment]
Looks go but it is still looking for a Item# when all i did was a membership renewal.
most of the time someone paying for membership or prosis are not placing a product order.

![image](https://cloud.githubusercontent.com/assets/26387044/25046028/c4bedb8e-20f4-11e7-837b-42484167c9f9.png)

If I type Membership and enter info under description, quantity and price, it works.

**Comment by sagarjagdish** [comment]
We have removed such validation, now order will send when you type Membership/Prosis Pro and enter info under description, quantity and price.

Please verify and let me know if there is any other change required in this.

**Comment by kbt1** [comment]
can you remove the 2 boxes marked Prosis Pro and Membership with description, quantity and price boxes.
they are not needed since it all works under Item #, Description, Quantity and Price.
![image](https://cloud.githubusercontent.com/assets/26387044/25232646/bbe15616-25a1-11e7-91b3-f0d225894f4c.png)

**Comment by omnitekinc** [comment]
@kbt1 Karen can you please let us know if this works.

**Comment by kbt1** [comment]
all works good.now i understand the form.
