### ISSUE TITLE
Membership tab

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#82]
I was looking at the membership tab and just curious why the start and end date fields are filled in instead of blank.

![image](https://cloud.githubusercontent.com/assets/26387044/24663632/186f66ce-191e-11e7-819c-ee76445d6979.png)

**Comment by omnitekinc** [comment]
I think that's just the default value but it's not activated. We can set it to emtpy

**Comment by kbt1** [comment]
can you set it empty.

**Comment by sagarjagdish** [comment]
set it empty and uploaded on stage. please verify and confirm.

**Comment by kbt1** [comment]
good.
