### ISSUE TITLE
Conference Attendees/Exhibitors

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#84]
Stella

Is there a way to mark a registration "Canceled"?
not sure we talked about this.

**Comment by omnitekinc** [comment]
Hi Karen,
No, we didn't know there's a Cancel option. Does it mean that person will be removed from the list? Or still stay on the list but listed as not attending.

**Comment by kbt1** [comment]
I just thought of it.
Just mark "Canceled" - stay on the list and $0 dollars.

**Comment by omnitekinc** [comment]
@kbt1: Do you cancel the entire registration or individual people inside 1 company?

**Comment by kbt1** [comment]
lets do individuals for attendees and tabletops.
be able to cancel an attendee and a tabletop fee.
i have had some people cancel due to conflicts.

**Comment by omnitekinc** [comment]
Hi Sagar, can you please add a Cancel Column on the end. And if Karen click "Cancel", it will change the word refund. And the total amount should be reflect on the invoice window.


![screen shot 2017-04-05 at 10 34 09 am](https://cloud.githubusercontent.com/assets/7178461/24718759/03f144be-19ec-11e7-9444-153e29197c64.png)
![screen shot 2017-04-05 at 10 36 15 am](https://cloud.githubusercontent.com/assets/7178461/24718762/0814568a-19ec-11e7-926b-cfa56af02193.png)

**Comment by sagarjagdish** [comment]
We have added function to cancel and refund attendee and uploaded on stage. please verify on stage and let me know if there is any issue.

**Comment by kbt1** [comment]
works good.
