### ISSUE TITLE
Membership and Prosis Invoices

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#86]
Can you add a check mark box and label it Start/Continue Monthly Payment Plan

Take out the line after Payment Information
Add the check mark box and label AFTER Check payable to AERA enclosed. (US Funds): $______________

![image](https://cloud.githubusercontent.com/assets/26387044/24708556/d2979418-19dc-11e7-8364-4bca3bc4370d.png)

**Comment by sagarjagdish** [comment]
We done with this change and uploaded on stage. Please verify and confirm.

![image](https://cloud.githubusercontent.com/assets/7322922/24956926/78b6fe86-1fa7-11e7-9cb2-abdd20fcf894.png)

**Comment by kbt1** [comment]
Looks good.

Just need to verify if membership and prosis both expire the same date, 1 invoice will print.
Can we even make it if they expire 1 or 2 months aparts to print 1 invoice?

Also, may need to discuss annual vs 6 month vs monthly renewal notices

Also, any record marked Monthly, i dont want any invoices pulled, we are coming up with a letter to send to monthly payment members when they expire about auto renewal. Will have to work on letter and get that to you when ready.

**Comment by sagarjagdish** [comment]
@omnitekinc  :

Just need to verify if membership and prosis both expire the same date, 1 invoice will print.
Can we even make it if they expire 1 or 2 months aparts to print 1 invoice?
=> If member having prosis & membership both then we are generating single invoice in print & email, without any condition. Please let me know if it will work.

Also, any record marked Monthly, i dont want any invoices pulled, we are coming up with a letter to send to monthly payment members when they expire about auto renewal. Will have to work on letter and get that to you when ready.
=> We have added check to stop bulk print and email for monthly payment members. If AERA want then they can print/email for monthly member individually. please let me know if there is any other change required in this.

**Comment by kbt1** [comment]
Since we are going to stop 6 Month Payments, can you set all Membership and Prosis records EXCEPT Monthly Payment people to Annual. 
Also, there has to be a condition to printing both membership and prosis invoices on 1 invoice.
If someones Prosis is expired from last year, we should only be invoicing for Membership this year.
Also, if expiration dates are months apart, they are not going to renew until it is actually due and this may cause confusion.

example:
![image](https://cloud.githubusercontent.com/assets/26387044/25589668/11fc4978-2e73-11e7-8a94-1bb54d0b71dd.png)

Why would I invoice for Prosis that expired last year.


The monthly payment check works.

**Comment by omnitekinc** [comment]
Karen, we will discuss this on our Wed call.

**Comment by kbt1** [comment]
ok Stella.

**Comment by omnitekinc** [comment]
Sagar, here is the logic for the invoices:
If Membership and Prosis Pro expired within 90 days then generate an invoice with both items. If it's over 90 days, just generate the invoice separately based on the individual expiration dates.

**Comment by sagarjagdish** [comment]
We have uploaded this logic on stage. Could you please verify and confirm our logic?

**Comment by kbt1** [comment]
works good.
