### ISSUE TITLE
"Membership Source" drop down box 

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#87]
add drop down box to membership labeled Membership Source
drop down box to include:
**New-Headquarters
New-Online
Reinstated
New-PRI
New-SEMA
New-AAPEX
New-Regional
New-EP**
**New-Other** -  ** if other selected, can another box pop up so i can type a source in?
**New-Rec**. by Member -  ** if selected, can another box pop up so i can type in a member#?
    ** if no to the above 2, then just do the source and i can always put a note in the comment field.

Also, is there a way to have access to add more sources in the future?
Kind of like updating fees in admin - be able to add a source for the drop down box?

**Comment by omnitekinc** [comment]
Hi Sagar, can add this dropdown int he membership. 

![screen shot 2017-04-05 at 10 26 14 am](https://cloud.githubusercontent.com/assets/7178461/24718361/955c0d46-19ea-11e7-8738-bfd7f4a2d652.png)

**Comment by omnitekinc** [comment]
@kbt1 We can add more category for you if you need it in the future, but there's no interface for you to add it yourself.

**Comment by kbt1** [comment]
please include additional sources for drop down box:

IMIS Show
Jobbers Open House
PAACE
Rottler Open House
Comp Mbrship

**Comment by kbt1** [comment]
Thanks Stella. I will make sure to have all categories figured out if we need more before we go live with the program. Otherwise, we will have you add more in the future.

**Comment by sagarjagdish** [comment]
We have added source drop down inside add/edit membership screen with all those option. please verify and confirm change on stage.

**Comment by kbt1** [comment]
When selecting New-Regional from drop down box, can another empty box open so we can type name of regional. Like when selecting New-Other, we can type something in another box.

![image](https://cloud.githubusercontent.com/assets/26387044/24967991/63d1fe48-1f71-11e7-98e0-df64285585b8.png)

**Comment by sagarjagdish** [comment]
done and uploaded on stage. now showing text box on New-Regional selection.

**Comment by kbt1** [comment]
works good.
