### ISSUE TITLE
Conferences Tab - Confirmations

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#89]
Most of the time we enter registration and send confirmation letters 2 weeks before the event.
I see that when you add a registration and send a confirmation, it marks the letter "sent".
However, if i go back into records and email a confirmation, it doesn't mark the letter "sent".

Can you change that so if at any time a letter is emailed, it will mark the letter "sent"

**Comment by kbt1** [comment]
Can you change that so if at any time a letter is emailed or printed, it will mark the letter "sent"

**Comment by sagarjagdish** [comment]
We have done with this change and now onward when any time a latter is emailed or printed, it's marked as "sent". 

Please verify our change and confirm.

**Comment by kbt1** [comment]
works
