### ISSUE TITLE
Membership-Join Date disappears 

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#9]
When you update the start and expiration date for an expired member the join date disappears and becomes --
Example: Mbr 42936 - US Seal had a join date before I went in and updated the start and expiration dates to reflect they re-joined.

**Comment by omnitekinc** [comment]
Hi Sagar,
Can you please take a look. Join date should be the date when the membership is created, and that date should not change. It's a record for AERA to know how long does someone has been a member.

**Comment by sagarjagdish** [comment]
We have looked and resolved this issue. I have also verified by updating Member# 12543.

http://71.13.159.202/aeramms_stage/addnewmember.aspx?id=11410&mode=view

**Comment by amandagoyette** [comment]
Seems to be working.
