### ISSUE TITLE
Email From Tech Queue

### ISSUE THREAD

**Issue by stevefox3781** [omnitekinc/AERA_MSS_Clients#94]
When I create a tech call and am going to email the member information, when I select Email under options and I hit the email button I get the following message...why is that. From the created tech call it should just open email when you click the Email button. 
![email](https://cloud.githubusercontent.com/assets/26387391/24958534/381d03e0-1f55-11e7-9823-0c93e2a5936a.jpg)

Also the Upload PDF File For Fax, can we just change that to Upload PDF File and you don't have to have the Fax selected? If I see something in a PDF File that the member does not want sent to them and just read over the phone, I would like to add it to the call so the other techs could see what was stated to the member.

**Comment by omnitekinc** [comment]
Sagar, is it possible to make email active even in the preview mode?

**Comment by omnitekinc** [comment]
@stevefox3781: Steve, you want to remove Fax on the dropdown, is that correct?

**Comment by sagarjagdish** [comment]
@omnitekinc  : We can enable email active in preview mode but can't active in add case. We need tech call stored information in database to send email and during add case we have nothing inside database until client click on Save button. We can make it enable once they click on Save.

Please let me know if you have any thoughts on this.

**Comment by stevefox3781** [comment]
No I want to leave that in the drop down. What I want is the verbiage changed on the button to read: **"Upload PDF File"** instead of "Upload PDF File For Fax". The only way we can upload a PDF File currently is if we have fax selected. We want to be able to add a PDF file no matter what is selected. 

Any questions, let em know.

**Comment by sagarjagdish** [comment]
Upload PDF File is now available for the all and it's uploaded on stage. Please verify and confirm.

Also please let me know if any other change required here.

![image](https://cloud.githubusercontent.com/assets/7322922/25045039/a8d8fe74-2147-11e7-8351-f11b63eb8fe9.png)

**Comment by stevefox3781** [comment]
Awesome! Works great!

Thank you,
