### ISSUE TITLE
Dues Processing - Batch Report

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#96]
I noticed the amount paid total and amount due total dont match up under Totals for Check but the Totals at the bottom of the report matches.

![image](https://cloud.githubusercontent.com/assets/26387044/24975371/ff8b703a-1f8a-11e7-8694-bed0a8fa6b76.png)

**Comment by sagarjagdish** [comment]
resolved this issue and uploaded on stage. Please verify and confirm.

**Comment by kbt1** [comment]
good.
