### ISSUE TITLE
Printing a Dues Invoice

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#98]
please change wording to:
`Renew my Membership
`
![image](https://cloud.githubusercontent.com/assets/26387044/24975925/12632926-1f8d-11e7-9ad2-158d406eb7cd.png)

**Comment by sagarjagdish** [comment]
I have set that label as per https://github.com/omnitekinc/AERA_MSS_Clients/issues/99 like "Annual Renewal" refer below image.

Please let me know if any change required.

![image](https://cloud.githubusercontent.com/assets/7322922/25044850/968077a8-2146-11e7-9627-73e9d5ac16cc.png)

**Comment by kbt1** [comment]
good.
