### ISSUE TITLE
Printing a Membership and Prosis Invoice

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#99]
Can you add before each expiration date what is expiring:
Example: Membership Expiration Date: 4/1/2017 or Prosis Pro Expiration Date: 4/1/2017
![image](https://cloud.githubusercontent.com/assets/26387044/24976083/b1c92d26-1f8d-11e7-9500-3146ae22621e.png)

Remove: Renew my service agreement
And somehow, can it be replaced with Annual Renewal or 6 Month Renewal depending on how their record is marked?

![image](https://cloud.githubusercontent.com/assets/26387044/24976176/0762d6ce-1f8e-11e7-8fb8-36d008c741c7.png)

**Comment by sagarjagdish** [comment]
Can you add before each expiration date what is expiring:
Example: Membership Expiration Date: 4/1/2017 or Prosis Pro Expiration Date: 4/1/2017
=> added Membership or  Prosis Pro  before expiration date and uploaded on stage.

Remove: Renew my service agreement
And somehow, can it be replaced with Annual Renewal or 6 Month Renewal depending on how their record is marked?
=> Shown renewal message as per selected plan like "Annual Renewal".

**Comment by kbt1** [comment]
good to go.

**Comment by kbt1** [comment]
can you also change wording to Monthly Renewal, NOT 1 Month Renewal.

![image](https://cloud.githubusercontent.com/assets/26387044/25053849/714d7516-211f-11e7-8d06-ae20d8a37e68.png)

**Comment by sagarjagdish** [comment]
We have changed wording from 1 Month Renewal to Monthly Renewal.

**Comment by kbt1** [comment]
and this should say Monthly Membership Service Fee
![image](https://cloud.githubusercontent.com/assets/26387044/25232768/2f3b3e24-25a2-11e7-8dcf-5e9af49ca85f.png)

**Comment by sagarjagdish** [comment]
@kbt1 : Okay we will update that text for Monthly, but what will be effective text for the 6 Month renewal from below.

"Semi Annual Membership Service Fee and Prosis Pro Service Agreement are due, to continue service please renew your membership and Prosis Pro."  

**OR**
 
"6 Month Membership Service Fee and Prosis Pro Service Agreement are due, to continue service please renew your membership and Prosis Pro."

**Comment by kbt1** [comment]
"6 Month Membership Service Fee and Prosis Pro Service Agreement are due, to continue service please renew your membership and Prosis Pro."

**Comment by sagarjagdish** [comment]
updated statement in invoice as suggested.
 
![image](https://cloud.githubusercontent.com/assets/7322922/25289604/ea15bc6a-26e7-11e7-924c-2e8682846838.png)

**Comment by kbt1** [comment]
Stella
Something to think about and we might need to have a meeting on invoicing alone.
**Wondering if we should set everyone except Monthly Payment Members at Annual Membership and then as people pay for 6 months, i can work on updating the database.** 
I dont want someone invoiced for 6 months membership and a full year Prosis. I think it should be 6 months of each or a full year of each. 

We WILL have monthly payment members that do monthly on membership and pay prosis in full or monthly on prosis and pay membership in full, and since we dont invoice monthly payment members, this shouldnt effect them. 
What do you think?

**Comment by omnitekinc** [comment]
We've decided we are not going to have 6 months membership moving forward. 
Karen, should we close this ticket?

**Comment by kbt1** [comment]
All membership and prosis records should be marked Annual EXCEPT monthly payment 
No 6 month payment plans.
